Repository laurent22/joplin, pull requests merged in 2019-01, with the labels that each got.

#1061 Update Norwegian translation
  CliClient/locales/nb_NO.po
Labels: translation

#1076 Update de_DE.po
  CliClient/locales/de_DE.po
Labels: translation

#1079 Update zh_CN translations
  CliClient/locales/zh_CN.po
Labels: translation

#1098 Update ru_RU translation
  CliClient/locales/ru_RU.po
Labels: translation

#1102 Update Japanese Translation.
  CliClient/locales/ja_JP.po
Labels: translation

#1054 fixed file url issue
  ReactNativeClient/lib/string-utils.js
Labels: bug

#1113 fix markdown code for checked checkbox
  ReactNativeClient/lib/MdToHtml.js
Labels: bug, essential

#1124 Update de_DE.po
  CliClient/locales/de_DE.po
Labels: translation

#1121 update Norwegian
  CliClient/locales/nb_NO.po
Labels: translation

#1119 update Italian
  CliClient/locales/it_IT.po
Labels: translation

#1125 Desktop: handle ESC key press to cancel the NotePropertiesDialog
  ElectronClient/app/gui/NotePropertiesDialog.jsx
Labels: desktop, enhancement

#1149 All: Update norwegian translations
  CliClient/locales/nb_NO.po
Labels: translation

#1157 All: Update Korean translations
  CliClient/locales/ko.po
Labels: translation

#1155 Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation
