Repository laurent22/joplin, pull requests merged in 2019-10, with the labels that each got.

#1925 Update Italian translation
  CliClient/locales/it_IT.po
Labels: translation

#1926 Improve Russian translation
  CliClient/locales/ru_RU.po
Labels: translation

#1928 Update localization de_DE.po
  CliClient/locales/de_DE.po
Labels: translation

#1929 CLI: Added some translations to es_ES.po
  CliClient/locales/es_ES.po
Labels: translation

#1930 Translation: update nb_NO
  CliClient/locales/nb_NO.po
Labels: translation

#1937 CLI: confirm encryption password
  CliClient/app/command-e2ee.js
Labels: cli

#1935 Mobile: no Dracula on mobile
  ReactNativeClient/lib/models/Setting.js
Labels: mobile

#1941 Add AUR repository
  README.md
Labels: documentation

#1933 Desktop: Larger search bar
  ElectronClient/app/gui/Header.jsx
Labels: desktop

#1940 Desktop: hide some toolbar buttons when editor hidden
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop

#1913 Mobile: Added Front Camera toggle when taking a picture with Joplin Camera
  ReactNativeClient/lib/components/CameraView.js
Labels: mobile

#1934 Desktop: set cancel as the default in dangerous operations
  ElectronClient/app/gui/SideBar.jsx
Labels: desktop

#1947 [es_ES ] Updating translation
  CliClient/locales/es_ES.po
Labels: translation

#1888 Desktop: Add loading animation to import/export
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/style.css
Labels: desktop

#1955 Fixed italian locale
  CliClient/locales/it_IT.po
Labels: translation

#1954 Minor fix to install script
  Joplin_install_and_update.sh
Labels: Linux

#1939 Mobile: confirm encryption password
  ReactNativeClient/lib/components/screens/encryption-config.js
Labels: mobile

#1949 Desktop: add checkmark to menu item, if Dev Tools are on
  ElectronClient/app/app.js
Labels: desktop

#1976 add setting: export.pdfPageSize
  ElectronClient/app/gui/NoteText.jsx
  ReactNativeClient/lib/models/Setting.js
Labels: desktop

#1982 API : update doc related to issue #1956
  readme/api.md
Labels: documentation

#1987 Desktop, Mobile: add typographer support
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/lib/renderers/MdToHtml.js
  readme/markdown.md
Labels: desktop, mobile

#1997 Translation Greek (el_GR)
  CliClient/locales/el_GR.po
Labels: translation

#1989 Translation - Korean Langauge
  CliClient/locales/ko.po
Labels: translation

#2000 Update ja_JP.po Japanese translation
  CliClient/locales/ja_JP.po
Labels: translation

#1981 Desktop: Stop watching external edits
  ReactNativeClient/lib/services/ExternalEditWatcher.js
Labels: desktop

#1984 Desktop: add context menu and menu item to create sub-notebook
  ElectronClient/app/app.js
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/SideBar.jsx
Labels: desktop

#2007 Update Czech translation
  CliClient/locales/cs_CZ.po
Labels: translation

#2009 update Italian translation
  CliClient/locales/it_IT.po
Labels: translation

#2033 Extended the danish translation
  CliClient/locales/da_DK.po
Labels: translation

#1991 Desktop: Add menu item to toggle note list #1988
  ElectronClient/app/app.js
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/Root.jsx
  ElectronClient/app/gui/SideBar.jsx
  ReactNativeClient/lib/models/Setting.js
Labels: desktop

#2003 CLI: Add command to list all tags for a note
  CliClient/app/autocompletion.js
  CliClient/app/command-tag.js
Labels: cli

#2004 Desktop: add Nord theme
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/gui/style/theme/nord.js
  ElectronClient/app/theme.js
  ReactNativeClient/lib/models/Setting.js
Labels: desktop

#2005 Desktop, Mobile: Update Markdown plugins: toc-done-right, anchor
  ElectronClient/app/package.json
  ReactNativeClient/package.json
Labels: desktop, mobile

#2014 Desktop: Allow custom CSS when printing #1918 (useCustomCss)
  ElectronClient/app/gui/NoteText.jsx
  README.md
Labels: desktop

#2026 Mobile: show alarm in correct date and time format
  ReactNativeClient/lib/components/select-date-time-dialog.js
Labels: mobile

#2029 Desktop: Fill X primary selection from the editor on text selection
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop

#2028 Desktop: Allow selecting what views should be available from the Layout button
  ElectronClient/app/app.js
  ReactNativeClient/lib/models/Setting.js
Labels: desktop
