Repository laurent22/joplin, pull requests merged in 2019-12, with the labels that each got.

#2135 Update norwegian translation
  CliClient/locales/nb_NO.po
Labels: translation

#2100 Desktop: Add highlight_mark token to Ace editor rules
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop, editor

#2150 Desktop: better icon size for about window
  ElectronClient/app/app.js
Labels: desktop, macOS

#2152 Clipper: update clipper icons
  Clipper/joplin-webclipper/icons/32-dev.png
  Clipper/joplin-webclipper/icons/32.png
  Clipper/joplin-webclipper/icons/48.png
  Clipper/joplin-webclipper/icons/96.png
Labels: clipper

#2163 Updated translation
  CliClient/locales/sv.po
Labels: translation

#2164 Russian translation update
  CliClient/locales/ru_RU.po
Labels: translation

#2099 Desktop: Allow for custom Joplin theme and Ace editor styles
  ElectronClient/app/app.js
  ElectronClient/app/gui/ConfigScreen.jsx
  README.md
  ReactNativeClient/lib/BaseApplication.js
  ReactNativeClient/lib/CssUtils.js
  ReactNativeClient/lib/layout-utils.js
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/lib/shim-init-node.js
  ReactNativeClient/lib/shim.js
Labels: desktop, editor

#2173 Public sharing (WIP)
  .eslintignore
  .gitignore
  .travis.yml
  BUILD.md
  CliClient/build.sh
  ElectronClient/app/gui/ConfigScreen.jsx
  ElectronClient/app/gui/DialogButtonRow.jsx
  ElectronClient/app/gui/DropboxLoginScreen.jsx
  ElectronClient/app/gui/EncryptionConfigScreen.jsx
  ElectronClient/app/gui/Header.jsx
  ElectronClient/app/gui/ImportScreen.jsx
  ElectronClient/app/gui/ItemList.jsx
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/Navigator.jsx
  ElectronClient/app/gui/NotePropertiesDialog.jsx
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/gui/OneDriveLoginScreen.jsx
  ElectronClient/app/gui/PromptDialog.jsx
  ElectronClient/app/gui/ShareNoteDialog.tsx
  ElectronClient/app/gui/StatusScreen.jsx
  ElectronClient/app/gui/utils/NoteListUtils.js
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
  ElectronClient/app/theme.js
  ReactNativeClient/lib/JoplinServerApi.ts
  ReactNativeClient/lib/SyncTargetNextcloud.js
  ReactNativeClient/lib/components/shared/config-shared.js
  ReactNativeClient/lib/locale.js
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/lib/registry.js
  ReactNativeClient/lib/synchronizer.js
  Tools/build-translation.js
  Tools/validate-translation.js
  appveyor.yml
  joplin.code-workspace
  package-lock.json
  package.json
  readme/nextcloud_app.md
  tsconfig.json
Labels: WIP

#2198 Fixng a couple typos
  readme/gsoc2020/ideas.md
Labels: documentation

#2194 Portuguese translation
  CliClient/locales/pt_PT.po
Labels: translation

#2201 Desktop, Mobile: update Katex to 0.11.1
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
  ReactNativeClient/package-lock.json
  ReactNativeClient/package.json
Labels: desktop, mobile

#2177 CLI: Update CliClient Node dependency to 10+
  CliClient/app/main.js
  CliClient/package.json
  README.md
  readme/terminal.md
Labels: cli

#2210 Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#2215 Traditional Chinese translate
  CliClient/locales/zh_TW.po
Labels: translation

#2211 Fixing errata in CliClient/locales/es_ES.po
  CliClient/locales/es_ES.po
Labels: translation

#2179 CLI: Add --export, --import, and --import-file flags to joplin config
  CliClient/app/command-config.js
Labels: cli

#2199 Desktop: Fix Goto scrolling (#2122)
  ElectronClient/app/gui/ItemList.jsx
Labels: desktop

#2231 update ar.po
  CliClient/locales/ar.po
Labels: translation

#2227 translate_korean
  CliClient/locales/ko.po
Labels: translation

#2245 Fix broken link
  readme/gsoc2020/index.md
Labels: documentation
