Repository laurent22/joplin, pull requests merged in 2019-08, with the labels that each got.

#1802 Translation : Korean Translation #2
  CliClient/locales/ko.po
Labels: translation

#1809 Translation: Translation Update pt_BR
  CliClient/locales/pt_BR.po
Labels: translation

#1813 Update: Updated Last Translator pt_BR
  CliClient/locales/pt_BR.po
Labels: translation

#1800 Discord Community Server
  README.md
Labels: documentation

#1821 Update nl_NL.po
  CliClient/locales/nl_NL.po
Labels: translation

#1791 CLI: fixes potential fatal error on start
  CliClient/app/app-gui.js
  CliClient/package.json
Labels: bug, essential, terminal

#1806 Desktop: Change template prompt to sans and sort templates
  ElectronClient/app/gui/PromptDialog.jsx
  ReactNativeClient/lib/TemplateUtils.js
Labels: desktop

#1810 Desktop: Use correct date format for templates
  ReactNativeClient/lib/TemplateUtils.js
Labels: bug, desktop

#1811 Desktop: Change localeCompare functiion for tags
  ElectronClient/app/gui/MainScreen.jsx
Labels: desktop

#1823 fix typo on encryption options screen
  CliClient/locales/ar.po
  CliClient/locales/bg_BG.po
  CliClient/locales/ca.po
  CliClient/locales/cs_CZ.po
  CliClient/locales/da_DK.po
  CliClient/locales/de_DE.po
  CliClient/locales/en_GB.po
  CliClient/locales/en_US.po
  CliClient/locales/es_ES.po
  CliClient/locales/eu.po
  CliClient/locales/fa.po
  CliClient/locales/fr_FR.po
  CliClient/locales/gl_ES.po
  CliClient/locales/hr_HR.po
  CliClient/locales/it_IT.po
  CliClient/locales/ja_JP.po
  CliClient/locales/joplin.pot
  CliClient/locales/ko.po
  CliClient/locales/nb_NO.po
  CliClient/locales/nl_BE.po
  CliClient/locales/nl_NL.po
  CliClient/locales/pl_PL.po
  CliClient/locales/pt_BR.po
  CliClient/locales/ro.po
  CliClient/locales/ru_RU.po
  CliClient/locales/sl_SI.po
  CliClient/locales/sr_RS.po
  CliClient/locales/sv.po
  CliClient/locales/tr_TR.po
  CliClient/locales/zh_CN.po
  CliClient/locales/zh_TW.po
  ElectronClient/app/gui/EncryptionConfigScreen.jsx
  ReactNativeClient/lib/components/screens/encryption-config.js
Labels: desktop, mobile, terminal, translation

#1828 Desktop: Fix Cinnamon Detection
  Joplin_install_and_update.sh
Labels: Linux

#1836 Update ca.po
  CliClient/locales/ca.po
Labels: translation
