Repository laurent22/joplin, pull requests merged in 2019-07, with the labels that each got.

#1710 Translation: minor fixes (de_DE)
  CliClient/locales/de_DE.po
Labels: translation

#1709 Update nl_NL.po
  CliClient/locales/nl_NL.po
Labels: translation

#1665 Android: Check filesystem permission if filesystem sync target is selected
  ReactNativeClient/lib/components/screens/config.js
Labels: android

#1705 fix: add override for ACE editor shortcut `Ctrl+K`
  ElectronClient/app/gui/NoteText.jsx
Labels: Linux, bug, desktop, editor, windows

#1741 bump modules: footnote, toc-done-right, anchor
  ElectronClient/app/package.json
  ReactNativeClient/package.json
Labels: desktop, mobile

#1749 mobile: show correct time/date (as specified in settings) for note properties
  ReactNativeClient/lib/components/screens/note.js
Labels: bug, mobile

#1647 Desktop: Added support for templates
  ElectronClient/app/app.js
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/gui/PromptDialog.jsx
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
  ElectronClient/app/style.css
  README.md
  ReactNativeClient/lib/BaseApplication.js
  ReactNativeClient/lib/TemplateUtils.js
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/lib/reducer.js
Labels: desktop

#1733 Desktop: Add solarized themes
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/theme.js
  ReactNativeClient/lib/models/Setting.js
Labels: desktop

#1769 Trans: Korean Language Support
  CliClient/locales/ko.po
Labels: translation

#1775 CLI: Add docs to clarify how to test
  CONTRIBUTING.md
Labels: documentation

#1765 Desktop: add `depthColor` for solarized light and dark themes
  ElectronClient/app/theme.js
Labels: desktop

#1653 Desktop: Create fileURLs via drag and drop
  CliClient/tests/pathUtils.js
  ElectronClient/app/gui/NoteText.jsx
  README.md
  ReactNativeClient/lib/path-utils.js
  ReactNativeClient/lib/shim-init-node.js
Labels: desktop, editor

#1708 Desktop,Cli: enex_to_md: support bold formatting in span tags
  CliClient/tests/enex_to_md/text_formatting.html
  CliClient/tests/enex_to_md/text_formatting.md
  CliClient/tests/enex_to_md/text_formatting_span_bold.html
  CliClient/tests/enex_to_md/text_formatting_span_bold.md
  ReactNativeClient/lib/import-enex-md-gen.js
Labels: desktop

#1744 fix: better handling of adding the title to print and export to PDF
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop
