Repository laurent22/joplin, pull requests merged in 2019-09, with the labels that each got.

#1853 Update Italian translation
  CliClient/locales/it_IT.po
Labels: translation

#1871 Update zh_CN.po Chinese translation
  CliClient/locales/zh_CN.po
Labels: translation

#1795 Desktop: Add `enex` to `html` export
  .gitignore
  CliClient/package-lock.json
  CliClient/package.json
  CliClient/tests/EnexToHtml.js
  CliClient/tests/enex_to_html/attachment.enex
  CliClient/tests/enex_to_html/attachment.html
  CliClient/tests/enex_to_html/checklist-list.enex
  CliClient/tests/enex_to_html/checklist-list.html
  CliClient/tests/enex_to_html/en-media--audio.enex
  CliClient/tests/enex_to_html/en-media--audio.html
  CliClient/tests/enex_to_html/en-media--image.enex
  CliClient/tests/enex_to_html/en-media--image.html
  CliClient/tests/enex_to_html/svg.enex
  CliClient/tests/enex_to_html/svg.html
  ElectronClient/app/app.js
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
  ElectronClient/package-lock.json
  ReactNativeClient/lib/import-enex-html-gen.js
  ReactNativeClient/lib/import-enex-md-gen.js
  ReactNativeClient/lib/import-enex.js
  ReactNativeClient/lib/resourceUtils.js
  ReactNativeClient/lib/services/InteropService.js
  ReactNativeClient/lib/services/InteropService_Importer_EnexToHtml.js
  ReactNativeClient/lib/services/InteropService_Importer_EnexToMd.js
Labels: desktop, enhancement

#1875 Translation - Korean Language Support
  CliClient/locales/ko.po
Labels: translation

#1901 Update nl_NL.po
  CliClient/locales/nl_NL.po
Labels: translation

#1902 Update ja_JP.po Japanese translation
  CliClient/locales/ja_JP.po
Labels: translation

#1915 Desktop: Code button now detects multiline
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop, editor
