Repository laurent22/joplin, pull requests merged in 2019-06, with the labels that each got.

#1616 Translation: update it_IT.po
  CliClient/locales/it_IT.po
Labels: translation

#1613 "Desktop" Complete Spanish translation
  CliClient/locales/es_ES.po
Labels: translation

#1597 Mobile: Bump version of multimd-tables for mobile
  ReactNativeClient/package.json
Labels: editor, mobile

#1601 Desktop: Clean up theme.js font settings
  ElectronClient/app/theme.js
Labels: desktop

#1603 Desktop/Mobile: Bump markdown-toc plugin version to 4.0.0
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
  ReactNativeClient/package-lock.json
  ReactNativeClient/package.json
Labels: desktop, mobile

#1612 CLI for Linux: Icon softcoding path and directory
  Joplin_install_and_update.sh
Labels: Linux

#1589 Desktop: Use the react-select library for tag input
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/PromptDialog.jsx
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
Labels: desktop

#1640 Update de_DE.po
  CliClient/locales/de_DE.po
Labels: translation

#1641 Backtick changes
  ElectronClient/app/app.js
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop, editor

#1638 add shortuct for tags (`Cmd+Opt+T` / `Ctrl+Alt+T`)
  ElectronClient/app/app.js
Labels: desktop

#1660 Localization: add bulgarian
  CliClient/locales/bg_BG.po
Labels: translation

#1659 Watch for rename events in the external editor and re-watch file
  ReactNativeClient/lib/services/ExternalEditWatcher.js
Labels: Linux, desktop

#1681 Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation

#1688 REST API notes: support is_todo
  CliClient/tests/services_rest_Api.js
  ReactNativeClient/lib/services/rest/Api.js
Labels: API
