Repository laurent22/joplin, pull requests merged in 2019-05, with the labels that each got.

#1479 Desktop: update chokidar to fix blank screen when returning from external editor
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
Labels: desktop

#1484 README update
  README.md
Labels: documentation

#1487 Update readme to warn about restarting the editor for userstyle
  README.md
Labels: documentation

#1503 CLI: CZech translation updated
  CliClient/locales/cs_CZ.po
Labels: translation

#1466 Android: Allow User-added CAs
  ReactNativeClient/android/app/src/main/AndroidManifest.xml
  ReactNativeClient/android/app/src/main/res/xml/network_security_config.xml
  readme/faq.md
Labels: mobile

#1507 Changed download links to v1.0.145
  README.md
Labels: documentation

#1532 add /%d to Fetching resources: %d
  CliClient/locales/ar.po
  CliClient/locales/ca.po
  CliClient/locales/cs_CZ.po
  CliClient/locales/da_DK.po
  CliClient/locales/de_DE.po
  CliClient/locales/en_GB.po
  CliClient/locales/en_US.po
  CliClient/locales/es_ES.po
  CliClient/locales/eu.po
  CliClient/locales/fr_FR.po
  CliClient/locales/gl_ES.po
  CliClient/locales/hr_HR.po
  CliClient/locales/it_IT.po
  CliClient/locales/ja_JP.po
  CliClient/locales/joplin.pot
  CliClient/locales/ko.po
  CliClient/locales/nb_NO.po
  CliClient/locales/nl_BE.po
  CliClient/locales/nl_NL.po
  CliClient/locales/pt_BR.po
  CliClient/locales/ro.po
  CliClient/locales/ru_RU.po
  CliClient/locales/sl_SI.po
  CliClient/locales/sv.po
  CliClient/locales/tr_TR.po
  CliClient/locales/zh_CN.po
  CliClient/locales/zh_TW.po
Labels: translation

#1524 Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation

#1539 [init] the first version of the fa.po file
  CliClient/locales/fa.po
Labels: translation

#1533 Github: updated Contributing.md
  CONTRIBUTING.md
Labels: documentation

#1534 Desktop: Fix for #1426, backticks added to auto-wrapping quotes.
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop, editor

#1537 Only delete the .desktop file if it will be replaced by the script
  Joplin_install_and_update.sh
Labels: Linux

#1545 use new forum link
  README.md
  Tools/build-website.js
Labels: documentation

#1504 Desktop: Fixes #1186, #1354. Clears search when clicking on a notebook.
  ElectronClient/app/gui/Header.jsx
Labels: desktop

#1586 Update multimd-table and enable options
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
  ReactNativeClient/lib/MdToHtml.js
Labels: desktop, mobile

#1596 Improved and fixed Persian (fa) translation
  CliClient/locales/fa.po
Labels: translation
