Repository laurent22/joplin, pull requests merged in 2019-02, with the labels that each got.

#1179 Russian translate
  CliClient/locales/ru_RU.po
Labels: translation

#1181 Desktop: Minor update to dark theme
  ElectronClient/app/theme.js
Labels: desktop

#1152 Clipper: bugfix, joplin icon not show up in Firefox using 32px size.
  Clipper/joplin-webclipper/manifest.json
Labels: clipper

#1173 Clipper: Feature added for storing urls
  Clipper/joplin-webclipper/content_scripts/index.js
  Clipper/joplin-webclipper/popup/src/App.js
Labels: clipper

#1234 [Mobile] Fix unclear Chinese translation.
  CliClient/locales/zh_CN.po
Labels: translation

#1235 Update de_DE.po
  CliClient/locales/de_DE.po
Labels: translation

#1148 Desktop: Add type 'info' and 'OK' button to update dialog when version up-to-date
  ElectronClient/app/checkForUpdates.js
Labels: desktop

#1206 New tag adding dialogue
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/PromptDialog.jsx
  ElectronClient/app/gui/TagItem.jsx
  ElectronClient/app/gui/TagList.jsx
  ElectronClient/app/style.css
  ElectronClient/app/theme.js
Labels: desktop

#1216 Desktop: Fix alt key using
  ElectronClient/app/app.js
Labels: desktop

#1230 Mobile: Set note webview background color
  ReactNativeClient/lib/components/note-body-viewer.js
Labels: mobile

#1231 add shortcut to start a sync
  ElectronClient/app/app.js
  ElectronClient/app/gui/SideBar.jsx
Labels: desktop, enhancement

#1252 change notebook icon in toolbar and search result
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop

#1253 when deleting notebook or tag, display name
  ElectronClient/app/gui/SideBar.jsx
Labels: desktop, enhancement

#1261 Update de_DE.po
  CliClient/locales/de_DE.po
Labels: translation

#1271 Updated pt_BR locale to correct unicode char escapes.
  CliClient/locales/pt_BR.po
Labels: translation
