Repository laurent22/joplin, pull requests merged in 2019-04, with the labels that each got.

#1348 macOS: make the menu more like a macOS menu
  ElectronClient/app/app.js
Labels: desktop

#1347 Toggle plugins
  ElectronClient/app/gui/note-viewer/index.html
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
  README.md
  ReactNativeClient/lib/MdToHtml.js
  ReactNativeClient/lib/MdToHtml/webviewLib.js
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/package-lock.json
  ReactNativeClient/package.json
Labels: desktop, mobile

#1391 add localization for English (United States) en_US
  CliClient/locales/en_US.po
Labels: translation

#1420 change shortcuts for 'Print' and 'Goto Anything'
  ElectronClient/app/app.js
  ElectronClient/app/plugins/GotoAnything.jsx
Labels: desktop

#1408 add option to use soft breaks for markdown rendering
  ReactNativeClient/lib/MdToHtml.js
  ReactNativeClient/lib/models/Setting.js
Labels: desktop, enhancement, mobile

#1439 update localization de_DE.po
  CliClient/locales/de_DE.po
Labels: translation

#1446 Readme: Change Download links from 1.0.142 to 1.0.143
  README.md
Labels: documentation

#1448 build-translation.js: hack to show en_US as 100%
  Tools/build-translation.js
Labels: documentation, enhancement
