Repository laurent22/joplin, pull requests merged in 2019-11, with the labels that each got.

#2054 Esperanto language 51% completed
  CliClient/locales/eo.po
Labels: translation

#2060 Translation: pt_BR.po
  CliClient/locales/pt_BR.po
Labels: translation

#2061 Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#2052 fix toc with special characters - finally
  ReactNativeClient/lib/renderers/MdToHtml.js
Labels: bug, desktop, mobile

#2035 Desktop, Mobile: Link resource Icon
  ElectronClient/app/package.json
  ReactNativeClient/lib/renderers/MdToHtml/rules/link_open.js
  ReactNativeClient/lib/renderers/noteStyle.js
  ReactNativeClient/package.json
Labels: desktop, mobile

#2063 CLI: update sharp tp v0.23.2 (for node 13 compatibility)
  CliClient/package-lock.json
  CliClient/package.json
Labels: cli

#2064 All: set user-agent header to Joplin/1.0
  ReactNativeClient/lib/WebDavApi.js
Labels: cli, desktop, mobile

#2062 Desktop: Prevent horizontal scrolling on Linux when a scrollbar is present in note list
  ElectronClient/app/gui/NoteList.jsx
Labels: Linux, desktop

#2056 Desktop: Add keyboard modes to editor (vim, emacs)
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/NoteText.jsx
  ReactNativeClient/lib/models/Setting.js
Labels: desktop

#2006 Desktop: Add new setting to show note counts for folders and tags
  CliClient/tests/models_Folder.js
  CliClient/tests/models_Tag.js
  ElectronClient/app/app.js
  ElectronClient/app/gui/SideBar.jsx
  ReactNativeClient/lib/BaseApplication.js
  ReactNativeClient/lib/components/shared/reduxSharedMiddleware.js
  ReactNativeClient/lib/folders-screen-utils.js
  ReactNativeClient/lib/joplin-database.js
  ReactNativeClient/lib/models/Folder.js
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/lib/models/Tag.js
Labels: desktop

#2086 Updated Czech translation
  CliClient/locales/cs_CZ.po
Labels: translation

#2108 Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation

#2115 Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#2116 Update pt_BR.po
  CliClient/locales/pt_BR.po
Labels: translation

#2106 correcting and expanding the markdown instructions for a link
  readme/markdown.md
Labels: documentation

#2123 Translation: Fix a typo in nl_NL.po
  CliClient/locales/nl_NL.po
Labels: translation

#2125 Translation: Finish translation of es_ES.po and standardize quotation marks format to guillemets
  CliClient/locales/es_ES.po
Labels: translation
