Repository laurent22/joplin, pull requests merged in 2019-03, with the labels that each got.

#1310 fix spelling mistake
  CONTRIBUTING.md
Labels: documentation

#1290 version info changes
  CliClient/locales/ca.po
  CliClient/locales/cs_CZ.po
  CliClient/locales/da_DK.po
  CliClient/locales/de_DE.po
  CliClient/locales/en_GB.po
  CliClient/locales/es_ES.po
  CliClient/locales/eu.po
  CliClient/locales/fr_FR.po
  CliClient/locales/gl_ES.po
  CliClient/locales/hr_HR.po
  CliClient/locales/it_IT.po
  CliClient/locales/ja_JP.po
  CliClient/locales/joplin.pot
  CliClient/locales/ko.po
  CliClient/locales/nb_NO.po
  CliClient/locales/nl_BE.po
  CliClient/locales/nl_NL.po
  CliClient/locales/pt_BR.po
  CliClient/locales/ro.po
  CliClient/locales/ru_RU.po
  CliClient/locales/sl_SI.po
  CliClient/locales/sv.po
  CliClient/locales/tr_TR.po
  CliClient/locales/zh_CN.po
  CliClient/locales/zh_TW.po
  ElectronClient/app/checkForUpdates.js
  ReactNativeClient/lib/components/screens/config.js
Labels: desktop, mobile

#1303 Update pt_BR.po
  CliClient/locales/pt_BR.po
Labels: translation

#1304 Add joplin.desktop file for xfce and mate desktops
  Joplin_install_and_update.sh
Labels: linux-distro-specific

#1316 Update de_DE.po
  CliClient/locales/de_DE.po
Labels: translation

#1318 Desktop: update jp translation
  CliClient/locales/ja_JP.po
Labels: translation

#1321 update zh-CN translation
  CliClient/locales/zh_CN.po
Labels: translation

#1333 Translation: complete norwegian, remove fuzzy entries
  CliClient/locales/nb_NO.po
Labels: translation

#1362 CLI: Update pt_BR.po
  CliClient/locales/pt_BR.po
Labels: translation

#1374 Update ru_RU.po
  CliClient/locales/ru_RU.po
Labels: translation

#1375 Update README.md
  README.md
Labels: documentation
