Repository laurent22/joplin, pull requests merged in 2020-07, with the labels that each got.

#3450 All: Translation: Update zh_TW.po
  CliClient/locales/zh_TW.po
Labels: translation

#3451 All: Translation: Update(improve) zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation

#2572 Added hierarchical/nested tags
  CliClient/app/autocompletion.js
  CliClient/app/command-tag.js
  CliClient/tests/models_Tag.js
  CliClient/tests/synchronizer.js
  Clipper/popup/src/App.js
  Clipper/popup/src/bridge.js
  ElectronClient/app.js
  ElectronClient/gui/MainScreen/commands/renameTag.ts
  ElectronClient/gui/MainScreen/commands/setTags.ts
  ElectronClient/gui/SideBar/SideBar.jsx
  ElectronClient/gui/TagList.jsx
  ElectronClient/plugins/GotoAnything.jsx
  ReactNativeClient/lib/components/screens/NoteTagsDialog.js
  ReactNativeClient/lib/components/screens/notes.js
  ReactNativeClient/lib/components/screens/tags.js
  ReactNativeClient/lib/components/shared/reduxSharedMiddleware.js
  ReactNativeClient/lib/components/shared/side-menu-shared.js
  ReactNativeClient/lib/components/side-menu-content.js
  ReactNativeClient/lib/import-enex.js
  ReactNativeClient/lib/joplin-database.js
  ReactNativeClient/lib/migrations/31.js
  ReactNativeClient/lib/models/Folder.js
  ReactNativeClient/lib/models/Migration.js
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/lib/models/Tag.js
  ReactNativeClient/lib/nested-utils.js
  ReactNativeClient/lib/reducer.js
  ReactNativeClient/lib/services/rest/Api.js
  ReactNativeClient/lib/string-utils.js
  ReactNativeClient/lib/synchronizer.js
  ReactNativeClient/root.js
Labels: high

#3468 Translation: Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation

#3470 Translation: Update zh_TW.po
  CliClient/locales/zh_TW.po
Labels: translation

#2815 Add AWS S3 sync
  .gitignore
  CliClient/package-lock.json
  CliClient/package.json
  CliClient/tests/file_api_driver.js
  CliClient/tests/test-utils.js
  ElectronClient/package-lock.json
  ElectronClient/package.json
  ReactNativeClient/lib/BaseApplication.js
  ReactNativeClient/lib/SyncTargetAmazonS3.js
  ReactNativeClient/lib/file-api-driver-amazon-s3.js
  ReactNativeClient/lib/file-api.js
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/package-lock.json
  ReactNativeClient/package.json
Labels: WIP, high

#3517 All: revised German translation
  CliClient/locales/de_DE.po
Labels: translation

#3523 Update tr_TR.po
  CliClient/locales/tr_TR.po
Labels: translation

#3526 All: Translation: Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#3518 fix linter error and thus CI pipeline
  ReactNativeClient/lib/SyncTargetAmazonS3.js
Labels: infra

#3512 Linux: Fix architecture check to only search within machine details
  Joplin_install_and_update.sh
Labels: linux

#3515 Desktop: Enforce that whitespace check for unindent checks the begining of the string
  ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useListIdent.ts
Labels: desktop, editor

#3522 Desktop: Split Codemirror setOptions into different effects
  ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
Labels: desktop, editor

#3542 All: Translation: Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation

#3549 All: Showcasing plugins as screenshots
  readme/markdown.md
  readme/plugin_images/abbr_plugin.jpg
  readme/plugin_images/deflist_plugin.jpg
  readme/plugin_images/emoji_plugin.jpg
  readme/plugin_images/footnote_plugin.jpg
  readme/plugin_images/fountain_plugin.jpg
  readme/plugin_images/insert_plugin.jpg
  readme/plugin_images/katex_plugin.jpg
  readme/plugin_images/mark_plugin.jpg
  readme/plugin_images/mermaid.jpg
  readme/plugin_images/multitable_plugin.jpg
  readme/plugin_images/softbreaks_plugin.jpg
  readme/plugin_images/sub_plugin.jpg
  readme/plugin_images/sup_plugin.jpg
  readme/plugin_images/toc_plugin.jpg
  readme/plugin_images/typographer_plugin.jpg
Labels: documentation

#3556 Doc: fixed a typo and added checked checkbox in Markdown Guide
  docs/images/Markdown_checkbox.jpg
  readme/markdown.md
Labels: documentation

#3577 Update pl_PL.po
  CliClient/locales/pl_PL.po
Labels: translation

#3579 All: Fixing and expanding Russian translation
  CliClient/locales/ru_RU.po
Labels: translation
