Repository laurent22/joplin, pull requests merged in 2020-03, with the labels that each got.

#2619 Desktop: Fix undefined showButtonLabels
  ElectronClient/gui/Header.jsx
Labels: desktop

#2626 DESKTOP:Code was not distinguishable from text
  ElectronClient/theme.js
Labels: gsoc-2020

#2657 Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#2565 Desktop: Add toggling functionality for bold, italics and code in Editor Toolbar
  ElectronClient/gui/NoteText.jsx
Labels: PR-tested, desktop, gsoc-2020, reviewed-todo

#2576 Desktop: preview mode fix
  ElectronClient/app.js
Labels: PR-tested, desktop, gsoc-2020, reviewed-todo

#2586 [mobile] webview: Enable debugging on browser.
  ReactNativeClient/android/app/src/main/java/net/cozic/joplin/MainApplication.java
Labels: gsoc-2020

#2668 Desktop : Tag Wrap Disabled
  ElectronClient/gui/TagList.jsx
Labels: desktop, gsoc-2020

#2628 Desktop: Disable Toggle Editor Layout Shortcut and Button in Empty Notebook
  ElectronClient/app.js
Labels: PR-tested, desktop, gsoc-2020

#2678 Update zh_CN.po : translate typo of "Editor" to "编辑器"
  CliClient/locales/zh_CN.po
Labels: translation

#2679 Translation: Add Thai language
  CliClient/locales/th_TH.po
Labels: translation

#2620 Desktop: Expand Tree on Search Result
  CliClient/tests/models_Folder.js
  ElectronClient/gui/NoteText.jsx
  ReactNativeClient/lib/models/Folder.js
Labels: PR-tested, desktop, gsoc-2020, reviewed-todo

#2713 Desktop: Markdown list indentation
  ElectronClient/gui/NoteText.jsx
Labels: desktop

#2724 Update: updated Serbian translation sr_RS
  CliClient/locales/sr_RS.po
Labels: translation

#2520 Desktop: Enhance notelist focus behaviour
  ElectronClient/gui/NoteList.jsx
Labels: PR-tested, desktop

#2711 Desktop: add button to About box to copy Joplin's information to the clipboard
  ElectronClient/app.js
  ElectronClient/bridge.js
Labels: PR-tested, desktop

#2649 API: Fix tags update on updating a note
  CliClient/app/command-apidoc.js
  CliClient/tests/services_rest_Api.js
  ReactNativeClient/lib/services/rest/Api.js
Labels: api, gsoc-2020

#2661 Enhancement: Build tools detecting script
  build_tools_check.js
  package.json
Labels: gsoc-2020

#2704 Removed export debug report button in iOS
  ReactNativeClient/lib/components/screens/config.js
Labels: gsoc-2020

#2720 added a new close function to close sidebar for an error and fixes #2715
  ReactNativeClient/lib/components/screens/note.js
Labels: gsoc-2020, mobile

#2744 added feature of select all and closes #2721
  ReactNativeClient/lib/components/screen-header.js
  ReactNativeClient/lib/reducer.js
Labels: gsoc-2020

#2730 Desktop: Batch delete for Notebooks added
  CliClient/tests/models_Folder.js
  CliClient/tests/models_Note.js
  ReactNativeClient/lib/models/Folder.js
Labels: desktop, gsoc-2020

#2563 Desktop: Added arrows to go front and back through note history
  CliClient/tests/integration_ForwardBackwardNoteHistory.js
  CliClient/tests/reducer.js
  ElectronClient/gui/MainScreen.jsx
  ElectronClient/gui/NoteList.jsx
  ElectronClient/gui/NoteText.jsx
  ElectronClient/gui/SideBar.jsx
  ElectronClient/plugins/GotoAnything.jsx
  ReactNativeClient/lib/reducer.js
Labels: WIP, gsoc-2020

#2708 Desktop: Fix button label wrapping
  ElectronClient/gui/Header.jsx
Labels: desktop, gsoc-2020

#2757 Mobile : The colour of the notes updated to OLED dark theme, instead of the dark theme
  ReactNativeClient/lib/components/global-style.js
Labels: gsoc-2020

#2642 Desktop: Fix `All notes` note list update bugs.
  CliClient/tests/integration_ShowAllNotes.js
  ReactNativeClient/lib/reducer.js
Labels: desktop

#2653 Desktop: add global shortcut to show/hide Joplin
  ElectronClient/ElectronAppWrapper.js
  README.md
Labels: PR-tested, desktop

#2776 Fixed menubar (Edit, Alt+E) shortcut problem while editing a note
  ElectronClient/gui/NoteText.jsx
Labels: desktop, windows

#2791 Update it_IT.po
  CliClient/locales/it_IT.po
Labels: translation

#2809 Fix : Remember last selected note
  CliClient/tests/reducer.js
  ReactNativeClient/lib/reducer.js
Labels: PR-tested, desktop, gsoc-2020

#2806 Update: updated German translation de_DE
  CliClient/locales/de_DE.po
Labels: translation

#2825 Windows Client Update Chinese simplified translation zh_CN
  CliClient/locales/zh_CN.po
Labels: translation

#2839 Translation: Update ru_RU.po
  CliClient/locales/ru_RU.po
Labels: translation

#2846 Improves brazilian portuguese translation
  CliClient/locales/pt_BR.po
Labels: translation

#2869 completed empty to 100%
  CliClient/locales/pl_PL.po
Labels: translation

#2782 Mobile: discard and save error after editing a note
  ReactNativeClient/lib/components/screens/note.js
Labels: gsoc-2020

#2828 Desktop: Fixed top margin of toolbar
  ElectronClient/gui/NoteText.jsx
Labels: gsoc-2020

#2876 Mobile: fixed css error in code block in oled theme in mobiles and closes #2859
  ReactNativeClient/lib/components/global-style.js
Labels: gsoc-2020

#2880 Turkish Translations updated
  CliClient/locales/tr_TR.po
Labels: translation

#2224 Mobile: Add list continuation & Markdown preview to editor
  ReactNativeClient/MarkdownEditor/Formats.js
  ReactNativeClient/MarkdownEditor/MarkdownEditor.js
  ReactNativeClient/MarkdownEditor/applyListFormat.js
  ReactNativeClient/MarkdownEditor/applyWebLinkFormat.js
  ReactNativeClient/MarkdownEditor/applyWrapFormat.js
  ReactNativeClient/MarkdownEditor/applyWrapFormatNewLines.js
  ReactNativeClient/MarkdownEditor/index.js
  ReactNativeClient/MarkdownEditor/renderButtons.js
  ReactNativeClient/MarkdownEditor/static/visibility.png
  ReactNativeClient/MarkdownEditor/utils.js
  ReactNativeClient/MarkdownEditor/webLinkValidator.js
  ReactNativeClient/lib/components/note-body-viewer.js
  ReactNativeClient/lib/components/screens/config.js
  ReactNativeClient/lib/components/screens/note.js
  ReactNativeClient/lib/joplin-renderer/MdToHtml.js
  ReactNativeClient/lib/joplin-renderer/noteStyle.js
  ReactNativeClient/lib/models/Setting.js
Labels: WIP, mobile, question-w4f

#2845 Mobile: fixed overlapping text in dropbox sync page
  ReactNativeClient/lib/components/screens/dropbox-login.js
Labels: gsoc-2020

#2914 Translation: Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#2868 Mobile: fixes the visiblity of "Path:" text
  ReactNativeClient/lib/components/screens/config.js
Labels: gsoc-2020

#2909 Mobile: fixed bold text not visible in dark theme
  ReactNativeClient/lib/components/global-style.js
Labels: gsoc-2020

#2918 Desktop : Prevent overflow on small window size
  ElectronClient/gui/NoteText.jsx
Labels: gsoc-2020

#2346 Desktop: md importer handle special chars in linked image name
  CliClient/tests/MdToMd.js
  CliClient/tests/md_to_md/sample-special-chars.md
  CliClient/tests/support/photo-åäö.jpg
  CliClient/tests/support/photo-åäö.jpg
  ReactNativeClient/lib/services/InteropService_Importer_Md.js
Labels: desktop, reviewed-todo

#2719 Desktop: Cleaning up the install / update script
  Joplin_install_and_update.sh
Labels: linux

#2686 Desktop: Go To Anything by body
  CliClient/tests/ArrayUtils.js
  CliClient/tests/StringUtils.js
  ElectronClient/plugins/GotoAnything.jsx
  ReactNativeClient/lib/ArrayUtils.js
  ReactNativeClient/lib/string-utils.js
Labels: gsoc-2020

#2931 Vietnamese Translation
  CliClient/locales/vi.po
Labels: translation
