Repository laurent22/joplin, pull requests merged in 2020-04, with the labels that each got.

#2971 Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation

#2973 Update Norwegian Translation
  CliClient/locales/nb_NO.po
Labels: translation

#2566 Desktop: Assign note to Notebook or Sub_Notebook functionality added
  ElectronClient/gui/MainScreen.jsx
  ElectronClient/gui/PromptDialog.jsx
  ElectronClient/gui/utils/NoteListUtils.js
Labels: desktop, gsoc-2020, upstream

#2978 Update it_IT.po
  CliClient/locales/it_IT.po
Labels: translation

#2983 Desktop: Fix a blank Goto Anything screen
  ElectronClient/plugins/GotoAnything.jsx
Labels: PR-tested, desktop

#2851 Mobile: fixed text issue on some devices
  ReactNativeClient/lib/components/global-style.js
  ReactNativeClient/lib/components/screens/config.js
Labels: gsoc-2020

#2910 Mobile: fixed the issue of export path text not visible in dark theme
  ReactNativeClient/lib/components/screens/config.js
Labels: gsoc-2020

#2989 Fix Korean language name: 한국어
  ReactNativeClient/lib/locale.js
Labels: infra

#2986 Translation: Update ko.po
  CliClient/locales/ko.po
Labels: translation

#3013 All: Translation: Update sv.po
  CliClient/locales/sv.po
Labels: translation

#3020 Traditional Chinese translate
  CliClient/locales/zh_TW.po
Labels: translation

#2737 Fixes offset in selection caused due to white spaces.
  ElectronClient/gui/NoteText.jsx
Labels: desktop, gsoc-2020

#2831 Desktop: Fixes todo-hover behaviour
  ElectronClient/gui/NoteList.jsx
  ElectronClient/style.css
Labels: gsoc-2020

#2905 Desktop: Disable ok button at empty input
  ElectronClient/gui/PromptDialog.jsx
Labels: gsoc-2020

#3055 Mobile: Fixes #2853: Fix white corners on switching themes in iOS
  ReactNativeClient/root.js
Labels: gsoc-2020

#3061 Mobile: Fixes #2798: Switch keyboard appearance with theme
  ReactNativeClient/lib/components/global-style.js
  ReactNativeClient/lib/components/screens/NoteTagsDialog.js
  ReactNativeClient/lib/components/screens/config.js
  ReactNativeClient/lib/components/screens/dropbox-login.js
  ReactNativeClient/lib/components/screens/encryption-config.js
  ReactNativeClient/lib/components/screens/folder.js
  ReactNativeClient/lib/components/screens/note.js
  ReactNativeClient/lib/components/screens/search.js
Labels: gsoc-2020

#3065 Update translation pt_BR
  CliClient/locales/pt_BR.po
Labels: translation

#3018 All: Translation: Update pt_PT.po
  CliClient/locales/pt_PT.po
Labels: translation

#3086 Update nl_BE.po
  CliClient/locales/nl_BE.po
Labels: translation

#3089 Desktop: Fixed KaTeX font issue in exported PDF
  ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js
Labels: PR-tested, desktop, gsoc-2020

#3105 Translation: Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#3104 Turkish translations updated
  CliClient/locales/tr_TR.po
Labels: translation

#3096 Desktop: Fixed the Goto Anything item list overflow
  ElectronClient/theme.js
Labels: gsoc-2020

#3123 Partial translation in French
  CliClient/locales/fr_FR.po
Labels: translation

#3128 Update Greek translation
  CliClient/locales/el_GR.po
Labels: translation

#2630 Desktop: add + to access 'Zoom In', allows to use the numpad
  ElectronClient/app.js
Labels: PR-tested, desktop, reviewed-todo

#2673 All: Fix format of geolocation data
  CliClient/tests/models_BaseItem.js
  ReactNativeClient/lib/models/BaseItem.js
Labels: high
