Repository laurent22/joplin, pull requests merged in 2020-08, with the labels that each got.

#3581 Desktop: Codemirror clean up list indent code
  ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useListIdent.ts
Labels: desktop, editor

#2995 Changes audio resource attachments to html5 audio controls
  .eslintignore
  .gitignore
  ReactNativeClient/lib/joplin-renderer/HtmlToHtml.js
  ReactNativeClient/lib/joplin-renderer/MdToHtml.js
  ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/audio.ts
  ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/html_image.js
  ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/image.js
  ReactNativeClient/lib/joplin-renderer/utils.js
  ReactNativeClient/lib/models/Resource.js
  ReactNativeClient/lib/models/Setting.js
Labels: high

#3252 Desktop: KeymapService: Initial implementation
  .eslintignore
  .gitignore
  CliClient/tests/services_KeymapService.js
  ElectronClient/app.js
  ElectronClient/plugins/GotoAnything.jsx
  ReactNativeClient/lib/services/CommandService.ts
  ReactNativeClient/lib/services/KeymapService.ts
  ReactNativeClient/lib/services/PluginManager.js
Labels: desktop, gsoc-2020

#3433 All: Resolves #1266: Add support for onedrive for Business
  ReactNativeClient/lib/SyncTargetOneDrive.js
  ReactNativeClient/lib/file-api-driver-onedrive.js
  ReactNativeClient/lib/onedrive-api.js
  ReactNativeClient/lib/registry.js
Labels: WIP, enhancement, sync

#3629 Add and fix some Spanish translations
  CliClient/locales/es_ES.po
Labels: translation

#3637 Translation: Update fa.po
  CliClient/locales/fa.po
Labels: translation

#3642 Update pt_BR.po
  CliClient/locales/pt_BR.po
Labels: translation

#3666 All: Fix typos and punctuation in Russian translation
  CliClient/locales/ru_RU.po
Labels: translation

#3668 Translation: Update pt_BR.po
  CliClient/locales/pt_BR.po
Labels: translation
