Repository laurent22/joplin, pull requests merged in 2020-09, with the labels that each got.

#3525 Desktop: Keyboard shortcut editor
  .eslintignore
  .gitignore
  CliClient/tests/services_KeymapService.js
  ElectronClient/app.js
  ElectronClient/gui/ConfigScreen.jsx
  ElectronClient/gui/KeymapConfig/KeymapConfigScreen.tsx
  ElectronClient/gui/KeymapConfig/ShortcutRecorder.tsx
  ElectronClient/gui/KeymapConfig/styles/index.ts
  ElectronClient/gui/KeymapConfig/utils/getLabel.ts
  ElectronClient/gui/KeymapConfig/utils/useCommandStatus.ts
  ElectronClient/gui/KeymapConfig/utils/useKeymap.ts
  ReactNativeClient/lib/components/shared/config-shared.js
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/lib/services/CommandService.ts
  ReactNativeClient/lib/services/KeymapService.ts
  ReactNativeClient/lib/services/PluginManager.js
Labels: WIP, desktop, gsoc-2020

#3718 Update Greek Translation
  CliClient/locales/el_GR.po
Labels: translation

#3728 All: Translation: Update ro.po
  CliClient/locales/ro.po
Labels: translation

#3761 All: Translation: Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#3770 All: Update German translation
  CliClient/locales/de_DE.po
Labels: translation

#3771 All: Translation: Update ko.po
  CliClient/locales/ko.po
Labels: translation

#3773 Turkish translations updated
  CliClient/locales/tr_TR.po
Labels: translation

#3776 Translation (fr_FR) : Fix typo in GotoAnything translation
  CliClient/locales/fr_FR.po
Labels: translation

#3717 Desktop: Fix missed highlighting when using the global search
  ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
  ReactNativeClient/lib/BaseApplication.js
Labels: version-1.2

#3745 Bump the mermaid version to 8.8.0
  ElectronClient/package.json
  ReactNativeClient/lib/joplin-renderer/assets/mermaid/mermaid.min.js
  ReactNativeClient/lib/joplin-renderer/package.json
Labels: version-1.2

#3778 All: Translation: Update ko.po
  CliClient/locales/ko.po
Labels: translation

#3798 Turkish Translations Updated
  CliClient/locales/tr_TR.po
Labels: translation

#3844 Full review of catalan translation
  CliClient/locales/ca.po
Labels: translation
