Repository laurent22/joplin, pull requests merged in 2020-06, with the labels that each got.

#3309 Translation: Update id_ID.po
  CliClient/locales/id_ID.po
Labels: translation

#3314 All: Translation: Update ja_JP
  CliClient/locales/ja_JP.po
Labels: translation

#3315 All: Translation: Update de_DE
  CliClient/locales/de_DE.po
Labels: translation

#3316 All: Translation: Update es_ES
  CliClient/locales/es_ES.po
Labels: translation

#3195 All: Resolves #173: Upload attachments > 4 MB when using OneDrive
  README.md
  ReactNativeClient/lib/file-api-driver-onedrive.js
  ReactNativeClient/lib/onedrive-api.js
  docs/index.html
Labels: high

#3262 install_and_update: document --silent
  Joplin_install_and_update.sh
Labels: linux

#2772 Desktop: Unindent empty list markup on Enter
  ElectronClient/gui/NoteEditor/NoteBody/AceEditor/AceEditor.tsx
  ElectronClient/gui/NoteEditor/NoteBody/AceEditor/utils/useListIdent.ts
Labels: PR-tested, desktop, high

#3358 Updated pt_BR translation
  CliClient/locales/pt_BR.po
Labels: translation

#3034 Desktop: Add default filename for jex export
  ElectronClient/InteropServiceHelper.js
Labels: desktop, high

#3378 Improved Linux install instructions
  README.md
Labels: documentation

#3390 Translation Update: bs_BA.po
  CliClient/locales/bs_BA.po
Labels: translation

#3391 Desktop, Mobile: fix link color for dark theme
  ReactNativeClient/lib/themes/dark.js
Labels: desktop, mobile

#3394 All: Translation: Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#3408 Update pt_BR.po
  CliClient/locales/pt_BR.po
Labels: translation

#3415 Turkish locales updated
  CliClient/locales/tr_TR.po
Labels: translation

#3432 Yandex disk removed from supported WEBDAV clients
  README.md
Labels: documentation

#3430 All: Translation: Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation
