Repository laurent22/joplin, pull requests merged in 2020-02, with the labels that each got.

#2403 Desktop: Support "select all" in the note list
  CliClient/tests/reducer.js
  ElectronClient/app/gui/NoteList.jsx
  ElectronClient/app/gui/SideBar.jsx
  ReactNativeClient/lib/reducer.js
Labels: desktop

#2443 Update German translation
  CliClient/locales/de_DE.po
Labels: translation

#2311 [WIP] Desktop: Emphasise note title
  ElectronClient/app/gui/NoteText.jsx
  ReactNativeClient/lib/welcomeAssets.js
Labels: desktop

#2329 Desktop: Note searchbox enhancements
  ElectronClient/app/gui/NoteSearchBar.jsx
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop

#2436 Desktop: Ignore no-sandbox start flag at joplin startup
  ReactNativeClient/lib/BaseApplication.js
Labels: desktop

#2432 Desktop: Fix #2365 by ensuring the main window is hidden when Joplin starts
  ElectronClient/app/ElectronAppWrapper.js
Labels: desktop

#2386 Desktop: Add `add or remove tags` for multiple notes.
  CliClient/tests/models_Tag.js
  ElectronClient/app/app.js
  ElectronClient/app/gui/MainScreen.jsx
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/gui/utils/NoteListUtils.js
  ReactNativeClient/lib/models/Tag.js
Labels: desktop

#2408 Desktop: Support list creation on multi-line selections
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop

#2410 Desktop: Do not show "could not print" warning dialog after cancelling print.
  ElectronClient/app/InteropServiceHelper.js
  ElectronClient/app/bridge.js
Labels: desktop

#2431 Desktop: Fix inconsistency when pasting text
  ElectronClient/app/gui/NoteText.jsx
Labels: desktop

#2404 Desktop: Support scrolling in the note list using keys (eg page up, page down)
  ElectronClient/app/gui/NoteList.jsx
Labels: desktop, reviewed-todo

#2453 Desktop: sort tags in drop-down list (when adding tags)
  ElectronClient/app/gui/MainScreen.jsx
Labels: PR-tested, desktop, tags

#2457 comment out console messages in WebDavApi.js
  ReactNativeClient/lib/WebDavApi.js
Labels: bug, cli

#2462 Updated Czech translation
  CliClient/locales/cs_CZ.po
Labels: translation

#2456 fix escaping of title when generating a markdown link
  CliClient/tests/markdownUtils.js
  ReactNativeClient/lib/markdownUtils.js
  ReactNativeClient/lib/models/BaseItem.js
Labels: PR-tested, bug

#2398 Desktop: Fix to update the note list if the selected tag is deleted.
  ReactNativeClient/lib/BaseApplication.js
Labels: desktop, question-w4f

#2466 use current year in About box (in the copyright text)
  ElectronClient/app/app.js
Labels: PR-tested, desktop

#2480 Desktop: Fix incorrect location format
  ElectronClient/app/gui/NotePropertiesDialog.jsx
Labels: PR-tested, bug, desktop

#2272 Clipper: Add ability to launch clipper window with shortcut
  Clipper/joplin-webclipper/background.js
  Clipper/joplin-webclipper/content_scripts/index.js
  Clipper/joplin-webclipper/manifest.json
  Clipper/joplin-webclipper/popup/src/App.css
  Clipper/joplin-webclipper/popup/src/App.js
  Clipper/joplin-webclipper/popup/src/bridge.js
  Clipper/joplin-webclipper/popup/src/index.js
Labels: clipper, reviewed-todo

#2468 Desktop: Support export of multiple notes to pdf files.
  ElectronClient/app/app.js
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/gui/utils/NoteListUtils.js
  ReactNativeClient/lib/fs-driver-base.js
Labels: desktop

#2479 Desktop: Fix `.desktop` file & force refresh
  Joplin_install_and_update.sh
Labels: linux

#2478 add katex font KaTeX_Size4-Regular.woff2
  ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/katex.js
  ReactNativeClient/lib/joplin-renderer/Tools/buildAssets.js
  ReactNativeClient/lib/joplin-renderer/assets/katex/fonts/KaTeX_Size4-Regular.woff2
Labels: PR-tested, bug, desktop, mobile

#2368 Mobile: Adding Oled dark theme
  ReactNativeClient/lib/components/global-style.js
  ReactNativeClient/lib/models/Setting.js
Labels: mobile, reviewed-todo

#2495 Extend copyright date range to 2020
  LICENSE
  README.md
  Tools/PortableAppsLauncher/Other/Source/License.txt
  readme/terminal.md
Labels: documentation

#2497 Update es_ES.po
  CliClient/locales/es_ES.po
Labels: translation

#2498 Add & Edit translations (nl_NL)
  CliClient/locales/nl_NL.po
Labels: translation

#2500 Desktop: Update Electron to 7.1.12
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
Labels: PR-tested, desktop

#2508 Desktop: Treat spaces as spaces in markdown editor.
  ElectronClient/app/gui/NoteText.jsx
Labels: PR-tested, desktop

#2512 Estonian lang
  CliClient/locales/et_EE.po
Labels: translation

#2247 Mobile: Add quick actions
  .eslintignore
  .gitignore
  CONTRIBUTING.md
  CliClient/package-lock.json
  ElectronClient/app/package-lock.json
  ReactNativeClient/QuickActions.ts
  ReactNativeClient/android/app/build.gradle
  ReactNativeClient/android/app/src/main/java/net/cozic/joplin/MainApplication.java
  ReactNativeClient/android/settings.gradle
  ReactNativeClient/ios/Joplin.xcodeproj/project.pbxproj
  ReactNativeClient/ios/Joplin/AppDelegate.m
  ReactNativeClient/lib/components/screens/note.js
  ReactNativeClient/main.js
  ReactNativeClient/package-lock.json
  ReactNativeClient/package.json
  ReactNativeClient/root.js
  package-lock.json
  package.json
Labels: mobile, reviewed-todo

#2522 update react-native-version-info to 1.0.1
  ReactNativeClient/package-lock.json
  ReactNativeClient/package.json
Labels: PR-tested, mobile

#2189 Desktop: Create a screen that list all the resouces (#592)
  .eslintignore
  .gitignore
  ElectronClient/app/app.js
  ElectronClient/app/gui/ResourceScreen.tsx
  ElectronClient/app/gui/Root.jsx
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
  ReactNativeClient/lib/joplin-database.js
Labels: desktop, reviewed-todo

#2526 Improve nl_NL Translation
  CliClient/locales/nl_NL.po
Labels: translation

#2525 Improve Simplified Chinese translation
  CliClient/locales/zh_CN.po
Labels: translation

#2534 Translation: update Korean translation
  CliClient/locales/ko.po
Labels: translation

#2537 Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#2541 Translation: Fix an sprintf format error in ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#2530 fix Resources menu item
  ElectronClient/app.js
Labels: PR-tested, bug, desktop

#2542 Made some changes to BUILD.md have better readability
  BUILD.md
Labels: documentation

#2472 Desktop: Implement "show all notes"
  .eslintrc.js
  CliClient/tests/integration_SmartFilters.js
  CliClient/tests/test-utils.js
  ElectronClient/gui/NoteText.jsx
  ElectronClient/gui/SideBar.jsx
  ReactNativeClient/lib/BaseApplication.js
  ReactNativeClient/lib/BaseModel.js
  ReactNativeClient/lib/folders-screen-utils.js
  ReactNativeClient/lib/models/Note.js
  ReactNativeClient/lib/models/SmartFilter.js
  ReactNativeClient/lib/reducer.js
  ReactNativeClient/lib/registry.js
  ReactNativeClient/lib/reserved-ids.js
  ReactNativeClient/lib/services/DecryptionWorker.js
  ReactNativeClient/lib/services/SearchEngine.js
Labels: desktop

#2557 Added missing translations and improved language (DE)
  CliClient/locales/de_DE.po
Labels: translation

#2551 Italian translation Update
  CliClient/locales/it_IT.po
Labels: translation

#2564 Desktop: Add docs for auto-reloading the Electron client
  BUILD.md
Labels: documentation

#2571 [ISSUE_TEMPLATE/bug_report.md] Fix typos and make it more convenient
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#2444 Desktop: Add word counter feature to notes
  .eslintignore
  .gitignore
  CliClient/package-lock.json
  ElectronClient/gui/MainScreen.jsx
  ElectronClient/gui/NoteContentPropertiesDialog.tsx
  ElectronClient/gui/NotePropertiesDialog.jsx
  ElectronClient/gui/NoteText.jsx
  ElectronClient/package-lock.json
  ElectronClient/package.json
  ElectronClient/theme.js
  ReactNativeClient/package-lock.json
  package-lock.json
Labels: PR-tested, desktop, reviewed-todo

#2474 Documentation: Added Styling Information To CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2531 Desktop: Use the strongly recommended asar packing on linux and macOS
  ElectronClient/package.json
Labels: PR-tested, desktop, linux, macOS

#2554 Desktop: Fix to update tag list when note is deleted.
  CliClient/tests/integration_TagList.js
  ReactNativeClient/lib/components/shared/reduxSharedMiddleware.js
Labels: desktop

#2562 Android: fixes http-url image render
  ReactNativeClient/android/app/src/main/res/xml/network_security_config.xml
Labels: gsoc-2020

#2577 Desktop: Speed up Webdav Sync on Linux
  ReactNativeClient/lib/WebDavApi.js
  ReactNativeClient/lib/shim-init-node.js
  ReactNativeClient/lib/shim-init-react.js
  ReactNativeClient/lib/shim.js
Labels: PR-tested, desktop, linux

#2582 DESKTOP: Fixes the bug where selected text was not being converted into bold text.
  ElectronClient/gui/NoteText.jsx
Labels: gsoc-2020

#2585 Add support for Rule of Hooks plugin (#2579)
  .eslintrc.js
  ElectronClient/gui/NoteContentPropertiesDialog.tsx
  package-lock.json
  package.json
Labels: gsoc-2020

#2503 change geolocation service to freegeoip.app
  ReactNativeClient/lib/geolocation-node.js
Labels: PR-tested, cli, desktop, enhancement

#2514 Desktop: fix window dimensions and position when the application start
  ElectronClient/ElectronAppWrapper.js
Labels: desktop, gsoc-2020
