Repository laurent22/joplin, pull requests merged in 2020-10, with the labels that each got.

#3855 Polish translation update
  CliClient/locales/pl_PL.po
Labels: translation

#3856 Update existing Persian translations and added some missing translations
  CliClient/locales/fa.po
Labels: translation

#3853 Bump mermaid to 8.8.1
  ElectronClient/package-lock.json
  ElectronClient/package.json
  ReactNativeClient/lib/joplin-renderer/assets/mermaid/mermaid.min.js
  ReactNativeClient/lib/joplin-renderer/package-lock.json
  ReactNativeClient/lib/joplin-renderer/package.json
  ReactNativeClient/package-lock.json
  ReactNativeClient/package.json
Labels: version-1.3

#3852 disabled emoji highlighting to fix bug
  ElectronClient/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
Labels: version-1.3

#3890 Update KR Translation
  CliClient/locales/ko.po
Labels: translation

#3880 Desktop: Added Thunderbird count
  ElectronClient/gui/SideBar/SideBar.tsx
Labels: desktop

#3924 pt-PT translation update.
  CliClient/locales/pt_PT.po
Labels: translation

#3929 Translate Spanish
  CliClient/locales/es_ES.po
Labels: translation

#3940 All: Updated Czech translation
  CliClient/locales/cs_CZ.po
Labels: translation

#3945 Tray: Exit -> Quit
  ElectronClient/app.ts
Labels: desktop

#3946 All: Resolves #3934 fix notebook filter
  ReactNativeClient/lib/services/searchengine/queryBuilder.ts
Labels: search

#3956 Updated italian translation
  CliClient/locales/it_IT.po
Labels: translation

#3947 All: Fix filters when language is in Korean
  ReactNativeClient/lib/services/searchengine/SearchEngine.js
Labels: search

#3967 All: Translation: Update ja_JP.po
  CliClient/locales/ja_JP.po
Labels: translation

#3978 All: Update es_ES.po language file
  CliClient/locales/es_ES.po
Labels: translation

#4012 Dutch translation updates
  CliClient/locales/nl_NL.po
Labels: translation

#3975 All: Resolves #3839: Change Markdown rendering to align with CommonMark spec
  CliClient/tests/MdToHtml.ts
  ReactNativeClient/lib/joplin-renderer/MdToHtml.ts
  ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/link_open.ts
  ReactNativeClient/lib/models/Setting.ts
  tsconfig.dev.json
  tsconfig.json
Labels: version-1.4
