Repository laurent22/joplin, pull requests merged in 2020-05, with the labels that each got.

#3172 Update italian locale
  CliClient/locales/it_IT.po
Labels: translation

#3082 Android: Fixed Export Profile Error
  ReactNativeClient/lib/components/screens/config.js
Labels: gsoc-2020

#2805 Add search feature in Help Menu (for mac users)
  ElectronClient/app.js
Labels: PR-tested, desktop, high, macOS

#2926 Linux: update install script to remove command -v check
  Joplin_install_and_update.sh
Labels: high, linux

#2945 Mobile: Disable sending serialized data over the react-native bridge when att…
  ReactNativeClient/lib/components/screens/note.js
Labels: high

#2957 Docs: Improved search type table
  README.md
Labels: high

#3113 Android: Prevent Joplin from crashing when downloading large files
  ReactNativeClient/lib/shim-init-react.js
Labels: high

#3136 Desktop: Fixes #3131: Long URL in Note Info Dialog
  ElectronClient/gui/NotePropertiesDialog.jsx
Labels: high

#2877 Mobile: Fixed notebook text overflow
  ReactNativeClient/lib/components/screen-header.js
Labels: gsoc-2020

#2919 Mobile: Fixed the switch and slider on config screen
  ReactNativeClient/lib/components/screens/config.js
Labels: gsoc-2020

#2955 All: Handle link in automatic title generation
  CliClient/tests/markdownUtils.js
  ReactNativeClient/lib/markdownUtils.js
  ReactNativeClient/lib/models/Note.js
Labels: gsoc-2020

#2988 Mobile : Disabled the header items when no note is selected
  ReactNativeClient/lib/components/Dropdown.js
  ReactNativeClient/lib/components/screen-header.js
Labels: gsoc-2020

#3006 Mobile : fixed the placeholder text color for the notebook title input in Edit Notebook screen
  ReactNativeClient/lib/components/screens/folder.js
Labels: gsoc-2020

#3069 CLI: Implemented configurable layout for terminal
  CliClient/app/app-gui.js
  ReactNativeClient/lib/models/Setting.js
Labels: gsoc-2020

#3075 Desktop: Fix focus on GotoAnything and Layout Switching
  ElectronClient/plugins/GotoAnything.jsx
Labels: gsoc-2020

#3084 Desktop: Fixed order of notebooks in moveToNotebook dialog
  CliClient/tests/models_Folder.js
  ElectronClient/gui/MainScreen.jsx
  ReactNativeClient/lib/models/Folder.js
Labels: desktop, gsoc-2020

#3111 Fixed the mermaid graph width
  ReactNativeClient/lib/joplin-renderer/MdToHtml/rules/mermaid_render.js
Labels: gsoc-2020

#3063 Desktop: Support Windows tiles
  Assets/SmallTile.svg
  Assets/Square150x150Logo.svg
  ElectronClient/build-win/Joplin.VisualElementsManifest.xml
  ElectronClient/build-win/icons/SmallTile.png
  ElectronClient/build-win/icons/Square150x150Logo.png
  ElectronClient/package.json
  Tools/generate-images.js
Labels: high

#2861 Desktop: Use system keychain for storing passwords
  CliClient/package.json
  CliClient/tests/models_Setting.js
  ElectronClient/package.json
  ReactNativeClient/lib/models/Setting.js
  ReactNativeClient/lib/shim-init-node.js
  ReactNativeClient/lib/shim.js
  ReactNativeClient/package.json
Labels: gsoc-2020

#2796 Mobile: Fix quick actions
  ReactNativeClient/lib/components/select-date-time-dialog.js
  ReactNativeClient/setUpQuickActions.ts
Labels: high

#3012 Desktop: Changing bold-text preview color for Aritim-dark theme
  ElectronClient/gui/style/theme/aritimDark.js
Labels: desktop, gsoc-2020

#3037 Desktop: Fixes #3009: Word/character counter includes Markdown syntax and HTML tags
  CliClient/package.json
  CliClient/tests/markdownUtils.js
  ElectronClient/gui/NoteContentPropertiesDialog.tsx
  ElectronClient/package.json
  ReactNativeClient/lib/markdownUtils.js
  ReactNativeClient/lib/string-utils.js
Labels: desktop, gsoc-2020

#2819 Add note history (back/forward)
  CliClient/tests/feature_NoteHistory.js
  CliClient/tests/reducer.js
  ElectronClient/gui/NoteEditor/NoteEditor.tsx
  ElectronClient/gui/NoteEditor/utils/types.ts
  ElectronClient/gui/NoteEditor/utils/useMessageHandler.ts
  ElectronClient/gui/NoteToolbar/NoteToolbar.tsx
  ReactNativeClient/lib/BaseApplication.js
  ReactNativeClient/lib/reducer.js
Labels: gsoc-2020

#2895 Desktop: Make sidebar resizable when note list is not displayed
  ElectronClient/gui/MainScreen.jsx
Labels: gsoc-2020

#3243 Updated German translation
  CliClient/locales/de_DE.po
Labels: translation

#3268 Polish translation improvements
  CliClient/locales/pl_PL.po
Labels: translation

#3277 Fixes some typos in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#3288 Translation: Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation

#3246 Translation : translate to bahasa indonesia
  CliClient/locales/id_ID.po
Labels: translation
