Repository laurent22/joplin, pull requests merged in 2020-01, with the labels that each got.

#2214 Desktop: Add external editor actions to the note context menu.
  ElectronClient/app/gui/NoteList.jsx
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/gui/utils/NoteListUtils.js
Labels: desktop

#2217 Desktop: Display selected tags under a note title
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/gui/TagList.jsx
  ReactNativeClient/lib/components/shared/reduxSharedMiddleware.js
Labels: desktop

#2295 Translation: completed Turkish translation and fixed minor errors
  CliClient/locales/tr_TR.po
Labels: translation

#2255 Desktop: Fix pdf export for current but unselected note.
  ElectronClient/app/app.js
  ElectronClient/app/gui/NoteText.jsx
  ElectronClient/app/gui/utils/NoteListUtils.js
Labels: desktop

#2314 update Electron to 7.1.9 - fix default button in dialog not working on macOS
  ElectronClient/app/package-lock.json
  ElectronClient/app/package.json
Labels: desktop

#2262 Desktop: when importing MD files create resources for local linked files
  CliClient/tests/MdToMd.js
  CliClient/tests/md_to_md/sample-duplicate-links.md
  CliClient/tests/md_to_md/sample-link-in-alt-text.md
  CliClient/tests/md_to_md/sample-no-links.md
  CliClient/tests/md_to_md/sample.md
  CliClient/tests/support/photo-two.jpg
  ReactNativeClient/lib/services/InteropService_Importer_Md.js
Labels: desktop

#2285 Added 'Yandex Disk' to the list of WebDAV-compatible services known to work with Joplin.
  README.md
Labels: documentation

#2340 Update Greek translation
  CliClient/locales/el_GR.po
Labels: translation

#2347 ru_RU translation updated and unified
  CliClient/locales/ru_RU.po
Labels: translation

#2323 Desktop: Fix empty pdf export
  ElectronClient/app/gui/NoteText.jsx
Labels: bug, desktop

#2367 Desktop: fix deprecation of getName() in Electron
  ElectronClient/app/ElectronAppWrapper.js
  ElectronClient/app/app.js
Labels: desktop

#2366 Update Italian translations
  CliClient/locales/it_IT.po
Labels: translation

#2376 Change to the documentation: Edits build instructions to avoid confusion
  BUILD.md
Labels: documentation

#2421 Update zh_CN.po
  CliClient/locales/zh_CN.po
Labels: translation
