Repository laurent22/joplin, pull requests merged in 2020-12, with the labels that each got.

#4037 Desktop: Focus editor after inserting datetime
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
  packages/app-desktop/gui/NoteEditor/commands/editorCommandDeclarations.ts
  packages/app-desktop/gui/NoteEditor/commands/focusElementNoteBody.ts
  packages/app-desktop/gui/NoteEditor/utils/useFormNote.ts
  packages/lib/services/commands/ToolbarButtonUtils.ts
Labels: desktop

#4156 All: Translation: Add Finnish fi_FI.po
  fi_FI.po
Labels: translation

#4168 All: Updated german translations
  packages/tools/locales/de_DE.po
Labels: translation

#4169 Update it_IT.po
  packages/tools/locales/it_IT.po
Labels: translation

#4195 Update zh_CN translation w.r.t latest pot
  packages/tools/locales/zh_CN.po
Labels: translation

#4200 All: Translation: Update ko.po
  packages/tools/locales/ko.po
Labels: translation

#4206 All: Translation: Update ja_JP.po
  packages/tools/locales/ja_JP.po
Labels: translation

#4193 Desktop, Mobile: Update Mermaid: 8.8.1 -> 8.8.4
  packages/app-mobile/pluginAssets/index.js
  packages/app-mobile/pluginAssets/mermaid/mermaid.min.js.base64.js
  packages/renderer/assets/mermaid/mermaid.min.js
  packages/renderer/package-lock.json
  packages/renderer/package.json
Labels: desktop, mobile

#4212 All: Translation: Update ru_RU.po
  packages/tools/locales/ru_RU.po
Labels: translation

#4247 Update it_IT.po
  packages/tools/locales/it_IT.po
Labels: translation

#4256 Update it_IT
  packages/tools/locales/it_IT.po
Labels: translation

#4258 Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#4263 Update zh_CN translation (2020-12-29)
  packages/tools/locales/zh_CN.po
Labels: translation

#4260 Updated es_ES.po
  packages/tools/locales/es_ES.po
Labels: translation

#4274 Turkish Translations updated
  packages/tools/locales/tr_TR.po
Labels: translation
