Repository laurent22/joplin, pull requests merged in 2021-12, with the labels that each got.

#5809 Tools: Use windows-latest to build desktop app on CI
  .github/workflows/github-actions-main.yml
Labels: infra

#5804 Desktop: Allow flags for native wayland
  packages/lib/BaseApplication.ts
Labels: linux

#5797 All: Use latest minor release of postgres 13 in docker-compose examples
  docker-compose.db-dev.yml
  docker-compose.server-dev.yml
  docker-compose.server.yml
Labels: server

#5793 Desktop: TinyMCE flashing white when switching notes/editor
  packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
Labels: desktop

#5829 Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#5771 Desktop: Changed note sort buttons to 3px radius
  packages/app-desktop/gui/NoteListControls/NoteListControls.tsx
Labels: desktop

#5750 Update fr_FR.po
  packages/tools/locales/fr_FR.po
Labels: translation

#5826 Desktop: Fix #5708: Scroll positions are remembered/preserved (Line-Percent-based Sync Scroll)
  .eslintignore
  .gitignore
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
  packages/app-desktop/gui/NoteEditor/NoteEditor.tsx
  packages/app-desktop/gui/NoteTextViewer.tsx
  packages/app-desktop/gui/note-viewer/index.html
  packages/app-desktop/gui/note-viewer/scrollmap.js
  packages/app-desktop/gui/utils/SyncScrollMap.ts
Labels: desktop

#5862 All: Translation: Update ja_JP.po
  packages/tools/locales/ja_JP.po
Labels: translation

#5876 Desktop: Fix #5872: Markdown search no longer scrolls to result
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Editor.tsx
Labels: desktop

#5868 Desktop: Fix sync-scroll comment to refer a correct URL
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
Labels: desktop

#5877 Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#5880 Update es_ES.po
  packages/tools/locales/es_ES.po
Labels: translation

#5883 Doc: Synchronous Scroll document
  Assets/WebsiteAssets/images/sync_scroll/abst-sync-lp2.png
  Assets/WebsiteAssets/images/sync_scroll/abst-wo-sync2.png
  Assets/WebsiteAssets/images/sync_scroll/md-editor-components-pr.png
  Assets/WebsiteAssets/images/sync_scroll/trans-e2l-l2v-2.png
  Assets/WebsiteAssets/images/sync_scroll/trans-v2l-l2e-2.png
  README.md
  readme/spec/sync_scroll.md
Labels: documentation

#5920 All: Documentation: Add yarn installation instruction
  BUILD.md
Labels: documentation

#5824 Server: Allow deleting complete user data
  packages/app-desktop/runForTesting.sh
  packages/server/package.json
  packages/server/public/css/main.css
  packages/server/schema.sqlite
  packages/server/src/db.ts
  packages/server/src/migrations/20211204191051_user_deletion.ts
  packages/server/src/models/BaseModel.ts
  packages/server/src/models/ChangeModel.ts
  packages/server/src/models/ItemModel.test.ts
  packages/server/src/models/ItemModel.ts
  packages/server/src/models/NotificationModel.ts
  packages/server/src/models/ShareModel.ts
  packages/server/src/models/ShareUserModel.ts
  packages/server/src/models/UserDeletionModel.test.ts
  packages/server/src/models/UserDeletionModel.ts
  packages/server/src/models/UserFlagModel.ts
  packages/server/src/models/UserItemModel.ts
  packages/server/src/models/UserModel.test.ts
  packages/server/src/models/UserModel.ts
  packages/server/src/models/factory.ts
  packages/server/src/models/utils/pagination.ts
  packages/server/src/routes/api/batch_items.ts
  packages/server/src/routes/api/debug.ts
  packages/server/src/routes/api/items.test.ts
  packages/server/src/routes/api/items.ts
  packages/server/src/routes/api/share_users.test.ts
  packages/server/src/routes/api/shares.test.ts
  packages/server/src/routes/index/tasks.ts
  packages/server/src/routes/index/user_deletions.ts
  packages/server/src/routes/index/users.ts
  packages/server/src/routes/routes.ts
  packages/server/src/services/BaseService.ts
  packages/server/src/services/TaskService.test.ts
  packages/server/src/services/TaskService.ts
  packages/server/src/services/UserDeletionService.test.ts
  packages/server/src/services/UserDeletionService.ts
  packages/server/src/services/database/types.ts
  packages/server/src/services/types.ts
  packages/server/src/tools/debugTools.ts
  packages/server/src/tools/generateTypes.ts
  packages/server/src/utils/errors.ts
  packages/server/src/utils/prettycron.testdisabled.ts
  packages/server/src/utils/prettycron.ts
  packages/server/src/utils/routeUtils.ts
  packages/server/src/utils/setupAppContext.ts
  packages/server/src/utils/setupTaskService.ts
  packages/server/src/utils/testing/fileApiUtils.ts
  packages/server/src/utils/time.ts
  packages/server/src/utils/urlUtils.ts
  packages/server/src/utils/views/table.ts
  packages/server/src/views/index/user.mustache
  packages/server/src/views/index/user_deletions.mustache
  packages/server/src/views/index/users.mustache
  packages/server/src/views/partials/tableRowItem.mustache
  yarn.lock
Labels: server

#5732 Desktop: Remove cm-strong css color specification
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/plugins/GotoAnything.tsx
  packages/lib/services/style/themeToCss.test.ts
  packages/lib/themes/aritimDark.ts
  packages/lib/themes/dark.ts
  packages/lib/themes/dracula.ts
  packages/lib/themes/light.ts
  packages/lib/themes/nord.ts
  packages/lib/themes/oledDark.ts
  packages/lib/themes/solarizedDark.ts
  packages/lib/themes/solarizedLight.ts
  packages/lib/themes/type.ts
  packages/renderer/defaultNoteStyle.js
  packages/renderer/noteStyle.ts
Labels: desktop

#5928 All: Update Catalan translation
  packages/tools/locales/ca.po
Labels: translation
