Repository laurent22/joplin, pull requests merged in 2021-11, with the labels that each got.

#5512 Desktop: Fix #2242: Sync-Scroll for Markdown Editor and Viewer
  .eslintignore
  .gitignore
  packages/app-cli/tests/MdToHtml.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/index.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
  packages/app-desktop/gui/NoteEditor/utils/useMarkupToHtml.ts
  packages/app-desktop/gui/NoteTextViewer.tsx
  packages/app-desktop/gui/note-viewer/index.html
  packages/app-desktop/gui/utils/SyncScrollMap.ts
  packages/renderer/MdToHtml.ts
  packages/renderer/MdToHtml/rules/source_map.ts
Labels: desktop

#5680 Updates on pt_BR.po file.
  packages/tools/locales/pt_BR.po
Labels: translation

#5682 Update of de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#5684 docs: terminal doc update to include local filesystem sync
  readme/terminal.md
Labels: documentation

#5688 Lost translations
  .github/scripts/run_ci.sh
  .github/workflows/github-actions-main.yml
  packages/tools/build-translation.js
Labels: infra

#5548 Desktop: Fixes flickering with local Note Search Bar
  packages/app-desktop/gui/note-viewer/index.html
Labels: desktop

#5437 Desktop: Sort Order Buttons and Per-Notebook Sort Order
  .eslintignore
  .gitignore
  packages/app-desktop/app.ts
  packages/app-desktop/gui/Button/Button.tsx
  packages/app-desktop/gui/MainScreen/commands/index.ts
  packages/app-desktop/gui/MainScreen/commands/toggleNotesSortOrderField.ts
  packages/app-desktop/gui/MainScreen/commands/toggleNotesSortOrderReverse.ts
  packages/app-desktop/gui/MainScreen/commands/togglePerFolderSortOrder.ts
  packages/app-desktop/gui/MenuBar.tsx
  packages/app-desktop/gui/NoteListControls/NoteListControls.tsx
  packages/app-desktop/gui/Sidebar/Sidebar.tsx
  packages/app-desktop/gui/menuCommandNames.ts
  packages/app-desktop/services/sortOrder/PerFolderSortOrderService.test.ts
  packages/app-desktop/services/sortOrder/PerFolderSortOrderService.ts
  packages/app-desktop/services/sortOrder/notesSortOrderUtils.test.ts
  packages/app-desktop/services/sortOrder/notesSortOrderUtils.ts
  packages/lib/BaseApplication.ts
  packages/lib/models/Setting.ts
Labels: desktop

#5606 Desktop: Resolves #4827,#5652: Fix and improve laggy scroll fix
  packages/app-desktop/gui/note-viewer/index.html
Labels: desktop

#5698 Desktop: add shortcut for bulleted list
  packages/app-desktop/gui/menuCommandNames.ts
  packages/lib/services/KeymapService.ts
Labels: desktop

#5695 Desktop: Fix #5694: Sync-scroll supports notes markuped in html
  packages/app-desktop/gui/utils/SyncScrollMap.ts
Labels: desktop

#5729 Update Crotian translation
  packages/tools/locales/hr_HR.po
Labels: translation

#5730 Update server README.md . From File to Filesystem
  packages/server/README.md
Labels: documentation

#5736 Linux: Fix .desktop file to make external links work on Ubuntu
  Joplin_install_and_update.sh
Labels: desktop

#5733 Update Swedish translation
  packages/tools/locales/sv.po
Labels: translation

#5737 Desktop: complete Chinese translation
  packages/tools/locales/zh_CN.po
Labels: translation

#5759 All: add date format YYYY/MM/DD
  packages/lib/models/Setting.ts
  packages/lib/models/dateTimeFormats.test.ts
Labels: enhancement, mobile, desktop, cli

#5587 Mobile (Android): Makes it impossible to have multiple instances of the app open
  packages/app-mobile/android/app/src/main/AndroidManifest.xml
Labels: android

#5312 All: aws-sdk-v3-js with better Error Handling
  README.md
  packages/app-mobile/index.js
  packages/app-mobile/ios/Podfile.lock
  packages/app-mobile/package-lock.json
  packages/app-mobile/package.json
  packages/app-mobile/utils/fs-driver-rn.ts
  packages/lib/SyncTargetAmazonS3.js
  packages/lib/components/shared/config-shared.js
  packages/lib/file-api-driver-amazon-s3.js
  packages/lib/fs-driver-dummy.js
  packages/lib/fs-driver-node.ts
  packages/lib/models/Resource.ts
  packages/lib/models/Setting.ts
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/testing/test-utils.ts
Labels: sync

#5743 Updated dependencies for Linux
  BUILD.md
Labels: documentation

#5798 [Android] Fix alarms
  packages/app-mobile/package-lock.json
  packages/app-mobile/package.json
  packages/app-mobile/services/AlarmServiceDriver.android.ts
Labels: android
