Repository laurent22/joplin, pull requests merged in 2021-08, with the labels that each got.

#5262 Update Swedish translation
  packages/tools/locales/sv.po
Labels: translation

#5251 Translation: Update id_ID.po (thanks to eresytter)
  packages/tools/locales/id_ID.po
Labels: translation

#5263 All:Updated norwegian translation
  packages/tools/locales/nb_NO.po
Labels: translation

#5252 Update mobile.md
  docs/images/JoplinMobileUI.jpg
  readme/mobile.md
Labels: documentation

#5246 All: Resolves #5244: Handles OneDrive throttling responses and sets User-Agent based on Microsoft best practices
  packages/lib/onedrive-api.ts
  packages/lib/testing/test-utils.ts
Labels: sync

#5212 All: Switch to aws-sdk-js-v3 resolves #4810 & resolves #4610
  packages/app-cli/package-lock.json
  packages/app-cli/package.json
  packages/app-mobile/index.js
  packages/app-mobile/ios/Podfile.lock
  packages/app-mobile/package-lock.json
  packages/app-mobile/package.json
  packages/app-mobile/utils/fs-driver-rn.ts
  packages/lib/SyncTargetAmazonS3.js
  packages/lib/components/shared/config-shared.js
  packages/lib/file-api-driver-amazon-s3.js
  packages/lib/fs-driver-dummy.js
  packages/lib/fs-driver-node.ts
  packages/lib/models/Resource.ts
  packages/lib/package-lock.json
  packages/lib/package.json
  packages/lib/testing/test-utils.ts
Labels: sync

#5270 Desktop: Added enabled check before adding to NoteListContextMenu list.
  packages/app-desktop/gui/utils/NoteListUtils.ts
Labels: desktop

#5291 All: Translation: Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#5294 Update Vietnamese translation
  packages/tools/locales/vi.po
Labels: translation

#5301 Update Swedish translation
  packages/tools/locales/sv.po
Labels: translation

#5314 Desktop: Resolves #5297: Add css classes for code in the markdown view
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
Labels: desktop

#5309 Server: Fix missing CSS file error in DevTools
  packages/server/public/css/index/changes.css
Labels: server

#5317 Update Swedish translation
  packages/tools/locales/sv.po
Labels: translation

#5323 Desktop: Linux: Remove dependency on lsb_release from install script
  Joplin_install_and_update.sh
Labels: linux

#5340 Update PT-BR Translate
  packages/tools/locales/pt_BR.po
Labels: translation

#5337 Server: Don't bother installing vim in the server docker image since its not needed to run
  Dockerfile.server
Labels: server

#5359 Desktop: Split code block class in two
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
Labels: enhancement, desktop

#5290 Desktop: Update the md export/import in preparation for yaml
  .eslintignore
  .gitignore
  packages/app-cli/tests/MdToMd.ts
  packages/app-cli/tests/md_to_md/sample-duplicate-links.md
  packages/app-cli/tests/md_to_md/sample-files.md
  packages/app-cli/tests/md_to_md/sample-link-in-alt-text.md
  packages/app-cli/tests/md_to_md/sample-special-chars.md
  packages/app-cli/tests/md_to_md/sample.md
  packages/app-cli/tests/support/photo sample.jpg
  packages/app-cli/tests/support/test_notes/md/sample spaces.md
  packages/app-cli/tests/support/test_notes/md/sample-anchor-link.md
  packages/app-cli/tests/support/test_notes/md/sample-cycles-a.md
  packages/app-cli/tests/support/test_notes/md/sample-cycles-b.md
  packages/app-cli/tests/support/test_notes/md/sample-duplicate-links.md
  packages/app-cli/tests/support/test_notes/md/sample-file-links.md
  packages/app-cli/tests/support/test_notes/md/sample-files.md
  packages/app-cli/tests/support/test_notes/md/sample-link-in-alt-text.md
  packages/app-cli/tests/support/test_notes/md/sample-link-title.md
  packages/app-cli/tests/support/test_notes/md/sample-md
  packages/app-cli/tests/support/test_notes/md/sample-no-extension.md
  packages/app-cli/tests/support/test_notes/md/sample-no-links.md
  packages/app-cli/tests/support/test_notes/md/sample-special-chars.md
  packages/app-cli/tests/support/test_notes/md/sample.html
  packages/app-cli/tests/support/test_notes/md/sample.md
  packages/lib/fs-driver-base.ts
  packages/lib/htmlUtils.ts
  packages/lib/markdownUtils.ts
  packages/lib/services/interop/InteropService.test.ts
  packages/lib/services/interop/InteropService.ts
  packages/lib/services/interop/InteropService_Exporter_Md.test.js
  packages/lib/services/interop/InteropService_Exporter_Md.ts
  packages/lib/services/interop/InteropService_Importer_Md.test.ts
  packages/lib/services/interop/InteropService_Importer_Md.ts
Labels: desktop

#5202 Server: Switch to node:16-bullseye and add python to the image to support building on non amd64 platforms
  Dockerfile.server
Labels: server

#5372 Turkish translations updated
  packages/tools/locales/tr_TR.po
Labels: translation

#5398 Update Traditional Chinese translation
  packages/tools/locales/zh_TW.po
Labels: translation
