Repository laurent22/joplin, pull requests merged in 2021-05, with the labels that each got.

#4852 Desktop: Fixes #4767: Create own copy of images while pasting
  packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
  packages/app-desktop/gui/NoteEditor/utils/contextMenu.ts
  packages/app-desktop/gui/NoteEditor/utils/resourceHandling.ts
Labels: desktop

#4832 Desktop: Resolves #4813 : skip empty lines while converting selection to list
  .eslintignore
  .gitignore
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.test.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts
Labels: desktop

#4930 All: Korean Language translation
  packages/tools/locales/ko.po
Labels: translation

#4954 All: add new date format YYMMDD
  .eslintignore
  .gitignore
  packages/app-cli/tests/dateTimeFormats.ts
  packages/lib/models/Setting.ts
  readme/terminal.md
Labels: cli, desktop, mobile

#4960 All: Translation: Update ja_JP.po
  packages/tools/locales/ja_JP.po
Labels: translation

#4961 All: Translation: Update el_GR.po
  packages/tools/locales/el_GR.po
Labels: translation

#4969 All: Translation: Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#4976 Update Korean Language
  packages/tools/locales/ko.po
Labels: translation

#4933 Desktop: Add classnames to DOM elements for theming purposes
  packages/app-desktop/gui/EncryptionConfigScreen.jsx
  packages/app-desktop/gui/NoteEditor/NoteEditor.tsx
  packages/app-desktop/gui/NoteEditor/NoteTitle/NoteTitleBar.tsx
  packages/app-desktop/gui/NoteListControls/NoteListControls.tsx
  packages/app-desktop/gui/NoteListItem.tsx
  packages/app-desktop/gui/NoteSearchBar.jsx
  packages/app-desktop/gui/PromptDialog.jsx
  packages/app-desktop/gui/SearchBar/SearchBar.tsx
  packages/app-desktop/gui/Sidebar/Sidebar.tsx
  packages/app-desktop/gui/ToggleEditorsButton/ToggleEditorsButton.tsx
  packages/app-desktop/plugins/GotoAnything.tsx
Labels: desktop

#4981 Doc:Fixed s3 bucket policy
  README.md
Labels: documentation

#4993 All: Translation: Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#5003 Updated Italian translation
  packages/tools/locales/it_IT.po
Labels: translation

#4957 Desktop: Fixes #4411: Count tags based on showCompletedTodos setting
  .eslintignore
  .gitignore
  packages/app-cli/tests/models_Tag.ts
  packages/app-desktop/gui/Sidebar/Sidebar.tsx
  packages/lib/JoplinDatabase.ts
Labels: desktop

#5011 Update it_IT.po
  packages/tools/locales/it_IT.po
Labels: translation

#5029 Update zh_TW.po
  packages/tools/locales/zh_TW.po
Labels: translation
