Repository laurent22/joplin, pull requests merged in 2021-09, with the labels that each got.

#5338 Server: Enable multi platform builds
  .github/workflows/github-actions-main.yml
  packages/tools/buildServerDocker.ts
  packages/tools/tool-utils.ts
Labels: server

#5302 Desktop: Handle URL links
  .eslintignore
  .gitignore
  packages/app-desktop/ElectronAppWrapper.ts
  packages/app-desktop/gui/MainScreen/MainScreen.tsx
  packages/app-desktop/gui/Sidebar/Sidebar.tsx
  packages/app-desktop/gui/utils/NoteListUtils.ts
  packages/app-desktop/main.js
  packages/app-desktop/package.json
  packages/lib/callbackUrlUtils.ts
Labels: enhancement, desktop

#5418 Update Swedish translation
  packages/tools/locales/sv.po
Labels: translation

#5419 update the german translation
  packages/tools/locales/de_DE.po
Labels: translation

#5401 Add Centos 7 for no sandbox
  Joplin_install_and_update.sh
Labels: linux

#5432 Update ca.po
  packages/tools/locales/ca.po
Labels: translation

#5448 Desktop, Mobile: Update Mermaid: 8.10.2 -> 8.12.1
  packages/app-desktop/package-lock.json
  packages/app-mobile/pluginAssets/highlight.js/atom-one-dark-reasonable.css.base64.js
  packages/app-mobile/pluginAssets/highlight.js/atom-one-light.css.base64.js
  packages/app-mobile/pluginAssets/index.js
  packages/app-mobile/pluginAssets/mermaid/mermaid.min.js.base64.js
  packages/lib/package-lock.json
  packages/renderer/assets/highlight.js/atom-one-dark-reasonable.css
  packages/renderer/assets/highlight.js/atom-one-light.css
  packages/renderer/assets/mermaid/mermaid.min.js
  packages/renderer/package-lock.json
  packages/renderer/package.json
Labels: mobile, desktop

#5452 All: Translation: Update fi_FI.po
  packages/tools/locales/fi_FI.po
Labels: translation

#5464 Translation: Update ar.po
  packages/tools/locales/ar.po
Labels: translation

#5476 Desktop: Properly quote variables in installer
  Joplin_install_and_update.sh
Labels: linux

#5445 All: Resolves #5444 Misinterpreted search term after filter in quotation marks
  packages/lib/services/searchengine/SearchFilter.test.js
  packages/lib/services/searchengine/filterParser.ts
Labels: search

#5478 macOS: add CM shortcut delWrappedLineLeft
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts
Labels: macOS

#5344 Desktop: Resolves #5233: Fire resize event whenever the layout changes
  packages/app-desktop/gui/MainScreen/commands/toggleNoteList.ts
  packages/app-desktop/gui/MainScreen/commands/toggleSideBar.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/index.ts
Labels: desktop

#5360 Desktop: Resolves #5299: Changed Note Search Bar warning background colour
  packages/app-desktop/gui/NoteSearchBar.jsx
Labels: desktop

#5484 Update Swedish translation
  packages/tools/locales/sv.po
Labels: translation

#5488 All: Translation: Update ja_JP.po
  packages/tools/locales/ja_JP.po
Labels: translation

#5504 All: Translation: Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#5486 Update French translation
  packages/tools/locales/fr_FR.po
Labels: translation

#5509 Update for Russian translation
  packages/tools/locales/ru_RU.po
Labels: translation
