Repository laurent22/joplin, pull requests merged in 2021-03, with the labels that each got.

#4622 Added Ukrainian translation
  packages/tools/locales/uk_UA.po
Labels: translation

#4642 All: Translation: Update pl_PL.po
  packages/tools/locales/pl_PL.po
Labels: translation

#4648 Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#4590 Android: Set min android version to 5 / sdk 21
  packages/app-mobile/android/build.gradle
Labels: android

#4589 Mobile: Upgrade react-native-share
  packages/app-mobile/package-lock.json
  packages/app-mobile/package.json
Labels: mobile

#4604 Android quick actions fix
  packages/app-mobile/root.tsx
Labels: android

#4625 Desktop: Speed up WebDAV/Nextcloud sync by ~30% (or even more)
  packages/lib/shim-init-node.js
Labels: desktop

#4607 Mobile: fix items shared to android not saved
  packages/app-mobile/components/screens/notes.js
Labels: mobile

#4631 Toggle math highlighting in editor
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
Labels: desktop, editor

#4632 Bring editor katex highlight in line with renderer
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
Labels: desktop, editor

#4636 remove branch name in detached head state
  packages/app-desktop/tools/compile-package-info.js
  packages/lib/versionInfo.ts
Labels: desktop, infra

#4609 Linux Install: SUID sandbox helper install patch
  Joplin_install_and_update.sh
Labels: linux

#4537 Desktop: Resolves #2810, Ctrl+Shift+B focuses on viewer when editor is not visible
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteTextViewer.tsx
Labels: desktop

#4624 Android: make Joplin resizeable
  packages/app-mobile/android/app/src/main/AndroidManifest.xml
Labels: android

#4670 Desktop: Fixes: #4612: Fix mermaid diagrams in WYSIWYG editor
  packages/renderer/MdToHtml/rules/mermaid.ts
Labels: desktop, editor

#4678 Readme : Fixed typos and grammatical errors in the readme files
  readme/conflict.md
  readme/debugging.md
  readme/gsoc2021/ideas.md
  readme/gsoc2021/index.md
  readme/nextcloud_app.md
  readme/plugins.md
  readme/rich_text_editor.md
Labels: documentation

#4707 All: Translation: Updated and completed Italian translation it_IT.po
  packages/tools/locales/it_IT.po
Labels: translation

#4717 Delete generated .js files
  packages/lib/BaseSyncTarget.js
  packages/lib/database.js
  packages/lib/file-api.js
  packages/tools/generate-database-types.js
Labels: infra

#4720 Locale de_DE Update
  packages/tools/locales/de_DE.po
Labels: translation

#4627 Desktop: Resolves #4614: Allow registering multiple settings in one call
  packages/app-cli/tests/services/plugins/api/JoplinSettings.ts
  packages/lib/services/plugins/api/JoplinSettings.ts
Labels: desktop

#4711 Desktop: Fixes #4683: Updating a disabled plugin enables it
  packages/app-desktop/gui/ConfigScreen/controls/plugins/useOnInstallHandler.test.ts
  packages/app-desktop/gui/ConfigScreen/controls/plugins/useOnInstallHandler.ts
Labels: desktop, plugins

#4703 Desktop: Fixes #4397: Fixed Broken Calendar Styling
  packages/app-desktop/style.css
Labels: desktop

#4689 Desktop: Add monospace enforcement for certain elements
  packages/app-desktop/app.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useJoplinMode.ts
  packages/lib/markdownUtils.ts
  packages/lib/models/Setting.ts
Labels: desktop, editor

#4668 Desktop: Set keep-alive for WebDAV/Nextcloud sync
  packages/lib/shim-init-node.js
Labels: desktop, sync

#4708 Doc: Update toc_plugin.md
  packages/app-cli/tests/support/plugins/toc/src/index.ts
  readme/api/tutorials/toc_plugin.md
Labels: documentation

#4745 All: Translation: Update fi_FI.po
  packages/tools/locales/fi_FI.po
Labels: translation

#4729 Mobile: Resolves #720: Add Sync only on Wi-Fi option
  .eslintignore
  .gitignore
  packages/app-cli/tests/registry.ts
  packages/app-mobile/android/app/src/main/AndroidManifest.xml
  packages/app-mobile/components/side-menu-content.js
  packages/app-mobile/package.json
  packages/app-mobile/root.tsx
  packages/lib/models/Setting.ts
  packages/lib/registry.ts
Labels: mobile

#4737 Change windows build tools install command
  BUILD.md
Labels: documentation

#4724 Desktop: Partially fixes #4602: Remove timestamp while copying images
  .eslintignore
  .gitignore
  packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/getCopyableContent.test.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/getCopyableContent.ts
Labels: desktop

#4771 All: Translation: Update zh_CN.po and zh_TW.po
  packages/tools/locales/zh_CN.po
  packages/tools/locales/zh_TW.po
Labels: translation

#4783 Correct typo in Welcome
  readme/welcome/1_welcome_to_joplin.md
Labels: documentation

#4782 Update README.md
  readme/spec/server_sharing.md
Labels: documentation
