Repository laurent22/joplin, pull requests merged in 2021-02, with the labels that each got.

#4449 Update zh_TW translation
  packages/tools/locales/zh_TW.po
Labels: translation

#4455 Turkish translations updated
  packages/tools/locales/tr_TR.po
Labels: translation

#4477 All: Translation: Update ar.po
  packages/tools/locales/ar.po
Labels: translation

#4467 All: Translation: Update es_ES.po
  packages/tools/locales/es_ES.po
Labels: translation

#4534 Translation: Update pl_PL.po
  packages/tools/locales/pl_PL.po
Labels: translation

#4541 Docs: Update in Build.md
  BUILD.md
Labels: documentation

#4550 Russian translation
  packages/tools/locales/ru_RU.po
Labels: translation

#4566 All: Translation: Update ko.po
  packages/tools/locales/ko.po
Labels: translation

#4571 Fix the link error, there is no server-v1.7.4
  readme/changelog_server.md
Labels: documentation

#4583 Update rich_text_editor.md
  readme/rich_text_editor.md
Labels: documentation

#4419 Plugin: Docs: Clarifying how to get/test the hello world plugin via scaffolding
  readme/api/get_started/plugins.md
Labels: documentation

#4421 Desktop: Development: Clarifying that dev mode is started from CLI
  readme/api/references/development_mode.md
Labels: documentation

#4509 Desktop: Enforce utf-8 charset for plugin scripts
  packages/app-desktop/services/plugins/plugin_index.html
Labels: desktop

#4557 Mobile: Fix incorrect field name when attaching a resource from share
  packages/lib/components/shared/note-screen-shared.js
Labels: mobile

#4584 Adding Hungarian translation
  packages/tools/locales/hu_HU.po
Labels: translation

#4496 Update Croatian translation
  packages/tools/locales/hr_HR.po
Labels: translation

#4599 Updating Brazilian Portuguese strings
  packages/tools/locales/pt_BR.po
Labels: translation

#4605 Locale PT-PT Update
  packages/tools/locales/pt_PT.po
Labels: translation
