Repository laurent22/joplin, pull requests merged in 2021-01, with the labels that each got.

#4278 Fix a few translation in zh-TW
  packages/tools/locales/zh_TW.po
Labels: translation

#4120 All: Resolves #3528: Upload Big Notes to Onedrive
  packages/lib/file-api-driver-onedrive.js
  packages/lib/onedrive-api.js
Labels: sync

#4259 Desktop: Add extra macos keys from #4257
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts
Labels: desktop, editor

#4273 Desktop: Add case insensitive sorting for Note Attachments tool
  packages/app-desktop/gui/ResourceScreen.tsx
Labels: desktop

#4277 Android: enable backup
  packages/app-mobile/android/app/src/main/AndroidManifest.xml
Labels: android

#4275 Android: fix images/resources long press - do not show menu on pinch zoom
  packages/app-mobile/components/NoteBodyViewer/hooks/useSource.ts
  packages/renderer/MdToHtml/linkReplacement.ts
  packages/renderer/MdToHtml/rules/image.ts
Labels: android

#4307 All: Translation: Update ja_JP.po
  packages/tools/locales/ja_JP.po
Labels: translation

#4315 Add Synology WebDAV Server to WebDAV-compatible services
  README.md
Labels: documentation

#4319 Update clipper.md interfer -> interfere
  readme/clipper.md
Labels: documentation

#4318 Desktop: Insert spellcheck replacement at correct location when the window is zoomed
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts
Labels: desktop, editor

#4322 Fix typo on json array definition
  packages/generator-joplin/README.md
Labels: documentation

#4309 actually toggle something ;-)
  packages/plugins/ToggleSideBars/src/index.ts
  packages/plugins/ToggleSideBars/src/manifest.json
Labels: plugins

#4387 Update Indonesian translation
  packages/tools/locales/id_ID.po
Labels: translation

#4306 Documentation update (released version v1.5.14)
  README.md
  readme/faq.md
  readme/nextcloud_app.md
  readme/note_history.md
  readme/plugins.md
  readme/rich_text_editor.md
  readme/terminal.md
  readme/welcome/3_synchronising_your_notes.md
Labels: documentation

#4410 All: Translation: Update ko.po
  packages/tools/locales/ko.po
Labels: translation

#4423 Corrected WSL link in readme
  readme/terminal.md
Labels: documentation

#4429 Update sr_RS.po
  packages/tools/locales/sr_RS.po
Labels: translation

#4437 Documentation: toggle [TOC] "yes"
  readme/markdown.md
Labels: documentation

#4438 Update sr_RS.po
  packages/tools/locales/sr_RS.po
Labels: translation

#4420 Chore: Updating template to match docs
  packages/generator-joplin/generators/app/templates/src/index.ts
Labels: plugins

#4443 All: Translation: Update ko.po
  packages/tools/locales/ko.po
Labels: translation

#4446 Update sr_RS.po
  packages/tools/locales/sr_RS.po
Labels: translation
