Repository laurent22/joplin, pull requests merged in 2021-06, with the labels that each got.

#5039 Update zh-TW
  packages/tools/locales/zh_TW.po
Labels: translation

#5043 All: Translation: Update ko.po
  packages/tools/locales/ko.po
Labels: translation

#5053 fix text of terms and privacy
  packages/server/src/routes/index/privacy.ts
  packages/server/src/routes/index/terms.ts
Labels: server

#5024 macOS: add 'Hide Others' and 'Show All' menu items
  packages/app-desktop/gui/MenuBar.tsx
Labels: macOS

#4914 Desktop: Fixes #4877: Incorrect list renumbering
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.test.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useCursorUtils.ts
Labels: desktop

#5073 Update Croatian translation
  packages/tools/locales/hr_HR.po
Labels: translation

#5074 All: Translation: Update cs_CZ.po
  packages/tools/locales/cs_CZ.po
Labels: translation

#5096 Translate es_ES.po to 100%
  packages/tools/locales/es_ES.po
Labels: translation

#5092 Update Mermaid: 8.8.4 -> 8.10.2
  packages/app-desktop/package-lock.json
  packages/app-mobile/ios/Podfile.lock
  packages/app-mobile/pluginAssets/index.js
  packages/app-mobile/pluginAssets/mermaid/mermaid.min.js.base64.js
  packages/lib/package-lock.json
  packages/renderer/assets/mermaid/mermaid.min.js
  packages/renderer/package-lock.json
  packages/renderer/package.json
Labels: desktop, mobile

#5112 All: Update Korean Translation
  packages/tools/locales/ko.po
Labels: translation

#5128 All: Translation: Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#5132 All: Translation: Update ja_JP.po
  packages/tools/locales/ja_JP.po
Labels: translation
