Repository laurent22/joplin, pull requests merged in 2021-04, with the labels that each got.

#4794 iOS: Fixes #3607: keyboards won't cover last line of note
  packages/app-mobile/components/screens/Note.tsx
Labels: iOS

#4781 Desktop: Resolves #4750 Disappearing text in markdown editor
  .eslintignore
  .gitignore
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useListIdent.ts
  packages/lib/.gitignore
  packages/lib/markdownUtils.test.ts
  packages/lib/markdownUtils.ts
Labels: desktop

#4799 Doc: update Desktop screenshots with newer version
  docs/images/AllClients.jpg
  docs/images/DemoDesktop.png
  docs/images/SubNotebooks.png
Labels: documentation

#4773 (Desktop) Fixes #4769: highlight existing text in global search field
  packages/app-desktop/gui/NoteListControls/commands/focusSearch.ts
Labels: desktop

#4390 Desktop: resolve #3695: Show notebook and note title in the title bar
  .eslintignore
  .gitignore
  packages/app-desktop/gui/Navigator.jsx
  packages/app-desktop/gui/getWindowTitle.test.ts
  packages/app-desktop/gui/getWindowTitle.ts
Labels: desktop

#4815 All: Translation: Update ja_JP.po
  packages/tools/locales/ja_JP.po
Labels: translation

#4718 Android: Fix sharing items from Joplin
  .eslintignore
  .gitignore
  packages/app-mobile/components/NoteBodyViewer/hooks/useOnResourceLongPress.ts
  packages/app-mobile/package-lock.json
  packages/app-mobile/package.json
  packages/app-mobile/root.tsx
  packages/app-mobile/utils/ShareUtils.ts
Labels: android

#4811 Desktop: add an option to renew the API token
  packages/app-desktop/gui/ClipperConfigScreen.jsx
  packages/lib/BaseApplication.ts
  packages/lib/services/EncryptionService.ts
Labels: desktop, enhancement

#4751 Desktop: Fixes #4697: Prevent Goto anything from changing notebooks
  packages/app-cli/tests/reducer.js
  packages/lib/reducer.ts
Labels: desktop

#4765 Update wording for font settings
  packages/lib/models/Setting.ts
Labels: desktop

#4777 Desktop: Resolves #4766: ENTER key no longer submits dialogs when a textarea is focused.
  packages/app-cli/tests/support/plugins/dialog/src/index.ts
  packages/app-desktop/services/plugins/hooks/useSubmitHandler.ts
Labels: desktop

#4826 All: Translation: Added Slovenian translation sl_SI.po
  packages/tools/locales/sl_SI.po
Labels: translation

#4834 Update Croatian translation
  packages/tools/locales/hr_HR.po
Labels: translation

#4844 Translation: Update ar.po
  packages/tools/locales/ar.po
Labels: translation

#4855 All: Translation: Update German translation
  packages/tools/locales/de_DE.po
Labels: translation

#4868 Added missing dutch translation
  packages/tools/locales/nl_NL.po
Labels: translation

#4875 All: Update Croatian translation
  packages/tools/locales/hr_HR.po
Labels: translation

#4878 Update id-ID translation
  packages/tools/locales/id_ID.po
Labels: translation

#4870 Desktop: Check if dataTransfer is non-null on drop
  packages/app-desktop/gui/NoteEditor/utils/useDropHandler.ts
Labels: desktop

#4492 iOS: Add share extension
  packages/app-mobile/ios/Joplin.xcodeproj/project.pbxproj
  packages/app-mobile/ios/Joplin.xcodeproj/xcshareddata/xcschemes/ShareExtension.xcscheme
  packages/app-mobile/ios/Joplin/AppDelegate.m
  packages/app-mobile/ios/Joplin/Info.plist
  packages/app-mobile/ios/Joplin/Joplin.entitlements
  packages/app-mobile/ios/Podfile
  packages/app-mobile/ios/Podfile.lock
  packages/app-mobile/ios/ShareExtension/Base.lproj/MainInterface.storyboard
  packages/app-mobile/ios/ShareExtension/Info.plist
  packages/app-mobile/ios/ShareExtension/JoplinCommonShareExtension.podspec
  packages/app-mobile/ios/ShareExtension/JoplinRNShareExtension.podspec
  packages/app-mobile/ios/ShareExtension/README.md
  packages/app-mobile/ios/ShareExtension/ShareExtension.entitlements
  packages/app-mobile/ios/ShareExtension/Source/Common/ShareData.h
  packages/app-mobile/ios/ShareExtension/Source/Common/ShareData.m
  packages/app-mobile/ios/ShareExtension/Source/Common/ShareExtensionConstants.h
  packages/app-mobile/ios/ShareExtension/Source/Common/ShareExtensionConstants.m
  packages/app-mobile/ios/ShareExtension/Source/RNShareExtension/ShareExtension.m
  packages/app-mobile/ios/ShareExtension/Source/ShareExtension/ShareViewController.h
  packages/app-mobile/ios/ShareExtension/Source/ShareExtension/ShareViewController.m
  packages/app-mobile/root.tsx
  packages/app-mobile/utils/ShareExtension.ts
  packages/app-mobile/utils/shareHandler.ts
Labels: iOS

#4755 Desktop: Fixes #4754: Roboto font in plugins
  README.md
  packages/app-desktop/index.html
  packages/app-desktop/services/plugins/UserWebviewIndex.html
  readme/api/references/plugin_theming.md
Labels: desktop

#4739 Desktop : Resolves #4736 Note list is empty if search field is cleared.
  packages/app-desktop/gui/SearchBar/SearchBar.tsx
Labels: desktop

#4742 Android: add option to disable TLS validation and allow self-signed certificates for WebDAV/NextCloud
  .eslintignore
  .gitignore
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/MainApplication.java
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/ssl/SslModule.java
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/ssl/SslPackage.java
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/ssl/SslUtils.java
  packages/app-mobile/components/screens/config.js
  packages/app-mobile/package-lock.json
  packages/app-mobile/package.json
  packages/app-mobile/root.tsx
  packages/app-mobile/utils/TlsUtils.ts
  packages/app-mobile/utils/shim-init-react.js
  packages/lib/SyncTargetNextcloud.js
  packages/lib/SyncTargetWebDAV.js
  packages/lib/WebDavApi.js
  packages/lib/components/shared/config-shared.js
  packages/lib/models/Setting.ts
Labels: android

#4806 Desktop: Skip invalid scroll positions when receiving CodeMirror scroll updates
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/index.ts
Labels: desktop, editor

#4873 Desktop: Add duplicate Line command
  packages/app-desktop/gui/MenuBar.tsx
  packages/app-desktop/gui/NoteEditor/commands/editorCommandDeclarations.ts
  packages/app-desktop/gui/menuCommandNames.ts
  packages/lib/services/KeymapService.ts
Labels: desktop, editor

#4887 All: Disable WebDAV response caching
  packages/lib/WebDavApi.js
Labels: sync

#4865 Desktop: Fixes #4529: Ghost panel and resizing issues
  packages/app-desktop/gui/ResizableLayout/utils/useLayoutItemSizes.test.ts
  packages/app-desktop/gui/ResizableLayout/utils/validateLayout.ts
Labels: desktop
