Repository laurent22/joplin, pull requests merged in 2022-08, with the labels that each got.

#6734 All: Translation: Update ko.po
  packages/tools/locales/ko.po
Labels: translation

#6727 Translation: Update zh_TW
  packages/tools/locales/zh_TW.po
Labels: translation

#6751 All: Translation: Update ko.po
  packages/tools/locales/ko.po
Labels: translation

#6737 Android: Fixes #6732: Don't reload the application on screen rotation
  packages/app-mobile/android/app/src/main/AndroidManifest.xml
Labels: android

#6738 iOS: Resolves #6731: Enable long-press menu
  packages/app-mobile/components/NoteBodyViewer/hooks/useSource.ts
Labels: iOS

#6782 Updated translation id_ID.po to 100%
  packages/tools/locales/id_ID.po
Labels: translation
