Repository laurent22/joplin, pull requests merged in 2022-02, with the labels that each got.

#6102 Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#6114 All: Updated translations for zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#6118 Desktop: Fixes #6108: add additional export menu item
  packages/app-desktop/gui/MenuBar.tsx
Labels: enhancement, desktop

#6097 Server: Resolves #6096: Use apt to install tini to fix/enable multi-platform support
  Dockerfile.server
Labels: server

#6178 Update Finnish translation
  packages/tools/locales/fi_FI.po
Labels: translation
