Repository laurent22/joplin, pull requests merged in 2022-01, with the labels that each got.

#5946 fix grammar and typos
  CONTRIBUTING.md
Labels: documentation

#5938 Docs: Update e2ee spec paths and links
  readme/spec/e2ee.md
Labels: documentation

#5950 Translations: Update Swedish translation
  packages/tools/locales/sv.po
Labels: translation

#5959 [Docs] A few more GSoC ideas
  readme/gsoc2022/ideas.md
Labels: documentation

#5815 Desktop: Implements a patch for multimd
  .yarn/patches/markdown-it-multimd-table-npm-4.1.1-47e334d4bd
  package.json
Labels: desktop, infra

#5832 Desktop: fix wording in settings
  packages/app-desktop/app.ts
  packages/lib/models/Setting.ts
Labels: desktop

#5923 Desktop: Fixes #5875: Show error on sync if S3 region is not set
  packages/lib/SyncTargetAmazonS3.js
  packages/lib/commands/synchronize.ts
  packages/lib/components/shared/side-menu-shared.js
Labels: desktop, sync

#5933 All: Don't automatically sign it to onedrive
  packages/lib/onedrive-api.ts
Labels: sync

#5929 Desktop: Fix #5918: Scroll jumps when images are rendered in Markdown Editor
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
Labels: desktop, editor

#5941 Desktop: Fix #5890: Scroll jump when checkbox is toggled in Viewer
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useScrollHandler.ts
  packages/lib/components/shared/note-screen-shared.js
Labels: desktop, editor

#5966 Doc: Add libvips dependency for Apple Silicon build instructions
  BUILD.md
Labels: documentation

#5956 Desktop: Clickable tags in Tag Bar
  packages/app-desktop/gui/TagItem.jsx
  packages/app-desktop/gui/TagList.tsx
  packages/lib/theme.ts
Labels: desktop, tags

#6009 [Docs] GSoC 2022 - email plugin idea
  readme/gsoc2022/ideas.md
Labels: documentation

#5984 Desktop: Linux: Prevent Desktop Environments to launch a new window
  Joplin_install_and_update.sh
Labels: desktop, linux

#5998 Desktop: Fix White space in the bottom of Add Tag Prompt
  packages/app-desktop/gui/PromptDialog.jsx
Labels: desktop

#6007 Clarify where to go to enable markdown plugins
  readme/markdown.md
Labels: documentation

#5994 Desktop: Fix issue #5953: search bar focus
  packages/app-desktop/gui/SearchBar/SearchBar.tsx
Labels: desktop

#6019 All: Update German translation
  packages/tools/locales/de_DE.po
Labels: translation

#6040 Desktop: Resolves #6035: Search selection fixes
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useEditorSearch.ts
  packages/app-desktop/gui/NoteEditor/utils/useNoteSearchBar.ts
  packages/app-desktop/gui/NoteEditor/utils/useSearchMarkers.ts
Labels: desktop, editor, search

#6046 Update pl_PL.po
  packages/tools/locales/pl_PL.po
Labels: translation

#6053 Updated Turkish Translations
  packages/tools/locales/tr_TR.po
Labels: translation

#6072 Docs: Add rich text editor limitation - lists within tables
  readme/rich_text_editor.md
Labels: documentation
