Repository laurent22/joplin, pull requests merged in 2023-10, with the labels that each got.

#7588 Mobile: js-draw-based image editor
  .eslintignore
  .gitignore
  packages/app-mobile/.gitignore
  packages/app-mobile/components/NoteBodyViewer/NoteBodyViewer.tsx
  packages/app-mobile/components/NoteBodyViewer/hooks/useEditPopup.test.ts
  packages/app-mobile/components/NoteBodyViewer/hooks/useEditPopup.ts
  packages/app-mobile/components/NoteBodyViewer/hooks/useOnMessage.ts
  packages/app-mobile/components/NoteBodyViewer/hooks/useOnResourceLongPress.ts
  packages/app-mobile/components/NoteBodyViewer/hooks/useSource.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/ImageEditor.tsx
  packages/app-mobile/components/NoteEditor/ImageEditor/autosave.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/isEditableResource.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/js-draw/applyTemplateToEditor.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/js-draw/createJsDrawEditor.test.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/js-draw/createJsDrawEditor.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/js-draw/startAutosaveLoop.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/js-draw/types.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/js-draw/watchEditorForTemplateChanges.ts
  packages/app-mobile/components/NoteEditor/ImageEditor/promptRestoreAutosave.ts
  packages/app-mobile/components/screens/Note.tsx
  packages/app-mobile/jest.config.js
  packages/app-mobile/package.json
  packages/app-mobile/root.tsx
  packages/app-mobile/tools/buildInjectedJs.ts
  packages/app-mobile/utils/shim-init-react.js
  packages/app-mobile/utils/types.ts
  packages/lib/components/shared/note-screen-shared.ts
  packages/lib/models/Setting.ts
  packages/renderer/MdToHtml.ts
  packages/renderer/MdToHtml/createEventHandlingAttrs.test.ts
  packages/renderer/MdToHtml/createEventHandlingAttrs.ts
  packages/renderer/MdToHtml/linkReplacement.ts
  packages/renderer/MdToHtml/rules/image.ts
  packages/renderer/tsconfig.json
  yarn.lock
Labels: mobile, editor

#8364 Mobile: Log screen: Add share menu item
  .eslintignore
  .gitignore
  packages/app-mobile/components/screens/LogScreen.tsx
  packages/app-mobile/components/screens/log.js
  packages/app-mobile/root.tsx
  packages/app-mobile/utils/ShareUtils.test.ts
  packages/app-mobile/utils/ShareUtils.ts
  readme/debugging.md
Labels: mobile

#8959 Translation: Update ar.po
  packages/tools/locales/ar.po
Labels: translation

#9114 Allow modifying a resource metadata only when synchronising
  .eslintignore
  .gitignore
  packages/app-cli/tests/support/sample.txt
  packages/app-cli/tests/support/sample2.txt
  packages/lib/JoplinDatabase.ts
  packages/lib/RotatingLogs.test.ts
  packages/lib/Synchronizer.ts
  packages/lib/models/BaseItem.test.ts
  packages/lib/models/BaseItem.ts
  packages/lib/models/Resource.test.ts
  packages/lib/models/Resource.ts
  packages/lib/services/database/types.ts
  packages/lib/services/synchronizer/Synchronizer.resources.test.ts
Labels: sync, v2.13

#9102 Turkish translations updated
  packages/tools/locales/tr_TR.po
Labels: translation

#9129 Translation: Update Brazilian Portuguese translation
  packages/tools/locales/pt_BR.po
Labels: translation

#9095 Fix typos in translations (PL)
  packages/tools/locales/pl_PL.po
Labels: translation
