Repository laurent22/joplin, pull requests merged in 2023-03, with the labels that each got.

#7856 docs: Fix minor typo in technical spec documentation
  readme/technical_spec.md
Labels: documentation

#7883 Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#7912 Desktop: Fixes #7907: Fixed height when controls are on a single row
  packages/app-desktop/gui/NoteListControls/NoteListControls.tsx
  packages/app-desktop/gui/NoteListWrapper/NoteListWrapper.tsx
  packages/lib/theme.ts
Labels: v2.10

#7945 All: Translation: Update fi_FI.po
  packages/tools/locales/fi_FI.po
Labels: translation

#7947 Update Croatian translation
  packages/tools/locales/hr_HR.po
Labels: translation

#7999 Update cs_CZ.po
  packages/tools/locales/cs_CZ.po
Labels: translation
