Repository laurent22/joplin, pull requests merged in 2023-11, with the labels that each got.

#9179 Desktop: Fixes #9130: Add Electron `--disable-gpu` flag to known flags
  packages/lib/utils/processStartFlags.ts
Labels: desktop

#9241 Clipper: Avoid errors when downloading media files without protocol
  .eslintignore
  .gitignore
  packages/lib/services/rest/routes/notes.test.ts
  packages/lib/services/rest/routes/notes.ts
Labels: clipper

#9244 Full translation support for Farsi/Persian
  packages/tools/locales/fa.po
Labels: translation

#9137 Desktop: Resolves #9136: Install script: Work around unprivlidged user namespace restrictions by adding the --no-sandbox flag to the launcher
  Joplin_install_and_update.sh
Labels: linux

#9269 All: Fixes #9151: Update note references at the end of the import process
  packages/app-cli/tests/support/test_notes/md/cycle-reference/sample-cycles-a.md
  packages/app-cli/tests/support/test_notes/md/cycle-reference/sample-cycles-b.md
  packages/lib/services/interop/InteropService_Importer_Md.test.ts
  packages/lib/services/interop/InteropService_Importer_Md.ts
  packages/lib/services/interop/InteropService_Importer_Md_frontmatter.test.ts
  packages/lib/services/interop/InteropService_Importer_Md_frontmatter.ts
Labels: bug, import

#9319 All: Resolves #9265: Add `no-constant-binary-expression` to eslint rules
  .eslintrc.js
Labels: enhancement

#9252 Clipper: add options to make fetchBlob exit faster, if needed
  packages/lib/services/rest/routes/notes.ts
  packages/lib/shim-init-node.js
Labels: clipper

#9364 Mobile: #9361: Fix to-dos options toggle don't toggle a rerender in
  packages/app-mobile/components/screens/Notes.tsx
Labels: bug, mobile, v2.13

#9415 Server: Fixes #9367: Redirect user from login to home if already logged
  packages/server/src/routes/index/login.test.ts
  packages/server/src/routes/index/login.ts
Labels: server
