Repository laurent22/joplin, pull requests merged in 2023-05, with the labels that each got.

#8162 Turkish Translations updated
  packages/tools/locales/tr_TR.po
Labels: translation

#8161 Russian translate
  packages/tools/locales/ru_RU.po
Labels: translation

#8169 Update sv.po
  packages/tools/locales/sv.po
Labels: translation

#8079 Desktop: Script: Check libfuse2 dependency
  Joplin_install_and_update.sh
Labels: desktop

#7953 Mobile: Fixes #7918: Use react-native-drawer-layout instead of react-native-side-menu-updated
  .eslintignore
  .eslintrc.js
  .gitignore
  packages/app-mobile/babel.config.js
  packages/app-mobile/components/SideMenu.ts
  packages/app-mobile/index.js
  packages/app-mobile/package.json
  packages/app-mobile/root.tsx
  yarn.lock
Labels: android

#8197 Update README.md
  README.md
Labels: documentation

#8205 Desktop: Fix the ldconfig dependency
  Joplin_install_and_update.sh
Labels: linux

#8219 Update Croatian translation
  packages/tools/locales/hr_HR.po
Labels: translation

#7980 Mobile: Implement parenting of notebooks
  .eslintignore
  .gitignore
  packages/app-mobile/components/FolderPicker.tsx
  packages/app-mobile/components/ScreenHeader.tsx
  packages/app-mobile/components/screens/folder.js
  packages/app-mobile/components/side-menu-content.tsx
Labels: mobile

#7772 Android: Fixes #7766: Updated foreground and monochrome icon to the vector drawable
  Assets/ImageSources/JoplinIconForeground.svg
  Assets/ImageSources/JoplinNotificationIcon.svg
  package.json
  packages/app-mobile/android/app/src/main/res/drawable-anydpi-v24/ic_notification.xml
  packages/app-mobile/android/app/src/main/res/drawable-hdpi/ic_notification.png
  packages/app-mobile/android/app/src/main/res/drawable-mdpi/ic_notification.png
  packages/app-mobile/android/app/src/main/res/drawable-xhdpi/ic_notification.png
  packages/app-mobile/android/app/src/main/res/drawable-xxhdpi/ic_notification.png
  packages/app-mobile/android/app/src/main/res/drawable/ic_launcher_foreground.png
  packages/app-mobile/android/app/src/main/res/drawable/ic_launcher_foreground.xml
  packages/app-mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  packages/app-mobile/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  packages/app-mobile/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  packages/app-mobile/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  packages/app-mobile/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  packages/app-mobile/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  packages/app-mobile/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  packages/app-mobile/services/AlarmServiceDriver.android.ts
  packages/react-native-alarm-notification/android/src/main/AndroidManifest.xml
  packages/react-native-alarm-notification/android/src/main/java/com/emekalites/react/alarm/notification/AlarmModel.java
  packages/react-native-alarm-notification/android/src/main/java/com/emekalites/react/alarm/notification/AlarmReceiver.java
  packages/react-native-alarm-notification/android/src/main/java/com/emekalites/react/alarm/notification/AlarmUtil.java
  packages/tools/generate-images.json
  packages/tools/generate-images.ts
  packages/tools/package.json
  yarn.lock
Labels: android
