Repository laurent22/joplin, pull requests merged in 2023-12, with the labels that each got.

#9454 Update Greek translation
  packages/tools/locales/el_GR.po
Labels: translation

#9501 Server: Remove direct dependecy from nanoid library
  packages/lib/uuid.ts
  packages/server/package.json
  packages/server/src/migrations/20190913171451_create.ts
  packages/server/src/models/BaseModel.ts
  packages/server/src/models/LockModel.ts
  packages/server/src/models/NotificationModel.ts
  packages/server/src/models/SessionModel.ts
  packages/server/src/models/SubscriptionModel.ts
  packages/server/src/models/TokenModel.ts
  packages/server/src/routes/admin/users.test.ts
  packages/server/src/routes/admin/users.ts
  packages/server/src/routes/api/users.ts
  packages/server/src/routes/index/password.test.ts
  packages/server/src/routes/index/signup.test.ts
  packages/server/src/routes/index/stripe.test.ts
  packages/server/src/routes/index/users.test.ts
  packages/server/src/routes/oauth2/authorize.ts
  packages/server/src/utils/storageConnectionCheck.ts
  packages/server/src/utils/testing/testUtils.ts
  packages/server/src/utils/uuidgen.ts
  yarn.lock
Labels: enhancement, server

#9503 Mobile: Fixes #9500: Fix font for the inbox email address not using the theme color
  packages/app-mobile/components/screens/ConfigScreen/ConfigScreen.tsx
  packages/app-mobile/components/screens/ConfigScreen/configScreenStyles.ts
Labels: bug, mobile

#9535 Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#9542 Update da_DK.po
  packages/tools/locales/da_DK.po
Labels: translation

#9609 update schinese translate
  packages/tools/locales/zh_CN.po
Labels: translation

#9627 Update pt_BR.po
  packages/tools/locales/pt_BR.po
Labels: translation
