Repository laurent22/joplin, pull requests merged in 2023-01, with the labels that each got.

#7643 All: Translation: Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#7641 Desktop: Fixes #7602: fix copy text with no selection
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
Labels: desktop, editor

#7630 Desktop: Fixes #7565: Text previously highlighted from searching in note remains highlighted
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/CodeMirror.tsx
Labels: desktop

#7665 complete russian locale
  packages/tools/locales/ru_RU.po
Labels: translation

#7690 Minor fixes and missing translations
  packages/tools/locales/pl_PL.po
Labels: translation

#7696 Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation
