Repository laurent22/joplin, pull requests merged in 2024-12, with the labels that each got.

#11461 All: Translation: Update uk_UA.po (thanks Andrii Poberezhnyi)
  packages/tools/locales/uk_UA.po
Labels: translation

#11505 Desktop: Reduce application size
  packages/renderer/package.json
Labels: desktop

#11513 Desktop: Fixes #11179: Fixed tags with same special unicode characters not matching
  packages/lib/models/Tag.test.ts
  packages/lib/models/Tag.ts
Labels: bug, desktop, v3.2

#11526 Desktop: Resolves: Generate .deb installer for Joplin Desktop
  packages/app-desktop/package.json
Labels: enhancement, desktop
