Repository laurent22/joplin, pull requests merged in 2024-03, with the labels that each got.

#9924 Add support for multiple columns note list
  .eslintignore
  .gitignore
  packages/app-cli/tests/support/plugins/note_list_renderer/src/index.ts
  packages/app-desktop/gui/MainScreen/MainScreen.tsx
  packages/app-desktop/gui/NoteList/NoteList.tsx
  packages/app-desktop/gui/NoteList/NoteList2.tsx
  packages/app-desktop/gui/NoteList/style.scss
  packages/app-desktop/gui/NoteList/utils/types.ts
  packages/app-desktop/gui/NoteList/utils/useDragAndDrop.ts
  packages/app-desktop/gui/NoteListHeader/NoteListHeader.tsx
  packages/app-desktop/gui/NoteListHeader/NoteListHeaderItem.tsx
  packages/app-desktop/gui/NoteListHeader/style.scss
  packages/app-desktop/gui/NoteListHeader/types.ts
  packages/app-desktop/gui/NoteListHeader/useDragAndDrop.test.ts
  packages/app-desktop/gui/NoteListHeader/useDragAndDrop.ts
  packages/app-desktop/gui/NoteListHeader/utils/getColumnTitle.ts
  packages/app-desktop/gui/NoteListHeader/utils/useContextMenu.ts
  packages/app-desktop/gui/NoteListHeader/utils/validateColumns.test.ts
  packages/app-desktop/gui/NoteListHeader/utils/validateColumns.ts
  packages/app-desktop/gui/NoteListItem/NoteListItem.tsx
  packages/app-desktop/gui/NoteListItem/utils/prepareViewProps.test.ts
  packages/app-desktop/gui/NoteListItem/utils/prepareViewProps.ts
  packages/app-desktop/gui/NoteListItem/utils/types.ts
  packages/app-desktop/gui/NoteListItem/utils/useItemEventHandlers.ts
  packages/app-desktop/gui/NoteListItem/utils/useRenderedNote.ts
  packages/app-desktop/gui/NoteListWrapper/NoteListWrapper.tsx
  packages/app-desktop/gui/utils/dragAndDrop.ts
  packages/app-desktop/style.scss
  packages/app-desktop/testPluginDemo.sh
  packages/lib/models/Setting.ts
  packages/lib/package.json
  packages/lib/services/noteList/defaultLeftToRightListRenderer.ts
  packages/lib/services/noteList/defaultListRenderer.ts
  packages/lib/services/noteList/defaultMultiColumnsRenderer.ts
  packages/lib/services/noteList/depNameToNoteProp.ts
  packages/lib/services/noteList/renderTemplate.test.ts
  packages/lib/services/noteList/renderTemplate.ts
  packages/lib/services/noteList/renderViewProps.test.ts
  packages/lib/services/noteList/renderViewProps.ts
  packages/lib/services/noteList/renderers.ts
  packages/lib/services/plugins/api/JoplinViewsNoteList.ts
  packages/lib/services/plugins/api/noteListType.ts
  packages/lib/theme.ts
  packages/lib/time.ts
  packages/tools/cspell/dictionary4.txt
  packages/utils/dom.ts
  packages/utils/object.test.ts
  packages/utils/object.ts
  packages/utils/package.json
  yarn.lock
Labels: desktop, plugins, v3.0

#10003 Desktop: Resolves #9980: Support Ctrl+Enter keyboard shortcut (Cmd+Enter on MacOS)
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/utils/useKeymap.ts
  packages/editor/CodeMirror/createEditor.ts
Labels: gsoc-2024

#10014 Desktop: Fixes #9985: Filter Sync Target Info Logs
  packages/lib/Synchronizer.ts
  packages/lib/services/synchronizer/syncInfoUtils.test.ts
  packages/lib/services/synchronizer/syncInfoUtils.ts
Labels: gsoc-2024

#10016 Desktop: Fixes #10007: Fixed Toggle Comment & Delete/Duplicate/Sort Line Options in Beta Editor
  .eslintignore
  .gitignore
  packages/editor/CodeMirror/CodeMirrorControl.test.ts
  packages/editor/CodeMirror/editorCommands/duplicateLine.test.ts
  packages/editor/CodeMirror/editorCommands/duplicateLine.ts
  packages/editor/CodeMirror/editorCommands/editorCommands.ts
  packages/editor/CodeMirror/editorCommands/sortSelectedLines.test.ts
  packages/editor/CodeMirror/editorCommands/sortSelectedLines.ts
  packages/editor/CodeMirror/editorCommands/swapLine.test.ts
  packages/editor/types.ts
Labels: gsoc-2024

#10005 Desktop: Resolves #9998: Fixed text wrapping in Spellcheck button
  packages/app-desktop/gui/NoteEditor/NoteTitle/NoteTitleBar.tsx
  packages/app-desktop/gui/ToolbarBase.tsx
  packages/app-desktop/gui/ToolbarButton/ToolbarButton.tsx
  packages/app-desktop/gui/ToolbarButton/styles/index.ts
Labels: gsoc-2024

#10048 iOS: Fixes #10047: Allow pasting URLs copied from the iOS share sheet
  packages/app-mobile/components/NoteEditor/CodeMirror/CodeMirror.ts
Labels: v2.14

#10038 Desktop: Fixes #9960: Creating a profile changes the language of Joplin
  packages/lib/BaseApplication.ts
Labels: gsoc-2024

#9585 Cli,Desktop,Mobile: Resolves #9465: Log user actions (deletions)
  .eslintignore
  .gitignore
  packages/app-cli/app/app.ts
  packages/app-cli/app/command-rmbook.ts
  packages/app-cli/app/command-rmnote.ts
  packages/app-cli/app/command-testing.ts
  packages/app-desktop/gui/MainScreen/commands/deleteFolder.ts
  packages/app-desktop/gui/MainScreen/commands/deleteNote.ts
  packages/app-desktop/gui/MainScreen/commands/permanentlyDeleteNote.ts
  packages/app-desktop/gui/ResourceScreen.tsx
  packages/app-mobile/components/ScreenHeader.tsx
  packages/app-mobile/components/screens/Note.tsx
  packages/app-mobile/components/side-menu-content.tsx
  packages/lib/BaseModel.ts
  packages/lib/Synchronizer.ts
  packages/lib/components/shared/reduxSharedMiddleware.ts
  packages/lib/models/BaseItem.ts
  packages/lib/models/Folder.ts
  packages/lib/models/Note.ts
  packages/lib/models/Resource.ts
  packages/lib/models/ResourceLocalState.ts
  packages/lib/models/Tag.ts
  packages/lib/models/utils/onFolderDrop.ts
  packages/lib/services/AlarmService.ts
  packages/lib/services/MigrationService.ts
  packages/lib/services/ResourceService.ts
  packages/lib/services/rest/routes/folders.ts
  packages/lib/services/rest/routes/notes.ts
  packages/lib/services/rest/utils/defaultAction.ts
  packages/lib/services/share/ShareService.ts
  packages/lib/services/synchronizer/ItemUploader.ts
  packages/lib/services/synchronizer/utils/handleConflictAction.ts
  packages/lib/services/trash/emptyTrash.ts
  packages/lib/services/trash/permanentlyDeleteOldItems.ts
  packages/lib/utils/ActionLogger.ts
  packages/utils/Logger.ts
Labels: v3.0

#9445 Desktop: Change Joplin Cloud login process to allow MFA via browser
  .eslintignore
  .gitignore
  packages/app-desktop/gui/ConfigScreen/ConfigScreen.tsx
  packages/app-desktop/gui/JoplinCloudLoginScreen.scss
  packages/app-desktop/gui/JoplinCloudLoginScreen.tsx
  packages/app-desktop/gui/Root.tsx
  packages/app-desktop/gui/SyncWizard/Dialog.tsx
  packages/app-desktop/main.scss
  packages/app-desktop/style.scss
  packages/lib/BaseApplication.ts
  packages/lib/JoplinServerApi.ts
  packages/lib/SyncTargetJoplinCloud.ts
  packages/lib/models/Setting.ts
  packages/lib/services/joplinCloudUtils.ts
  packages/lib/types.ts
Labels: enhancement, desktop, v3.0

#9788 Clipper: Add capability of limiting downloads
  .eslintignore
  .gitignore
  packages/lib/downloadController.ts
  packages/lib/errors.ts
  packages/lib/package.json
  packages/lib/services/rest/routes/notes.ts
  packages/lib/shim-init-node.ts
  packages/utils/bytes.ts
  yarn.lock
Labels: v3.0

#9935 Desktop: Improve beta editor support for the Rich Markdown plugin
  .eslintignore
  .gitignore
  packages/app-desktop/app.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v5/Editor.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/Editor.tsx
  packages/editor/CodeMirror/CodeMirror5Emulation/CodeMirror5BuiltInOptions.ts
  packages/editor/CodeMirror/CodeMirror5Emulation/CodeMirror5Emulation.ts
  packages/editor/CodeMirror/CodeMirror5Emulation/Decorator.ts
  packages/editor/CodeMirror/markdown/decoratorExtension.ts
  packages/editor/CodeMirror/pluginApi/PluginLoader.ts
  packages/editor/CodeMirror/theme.ts
  packages/tools/cspell/dictionary4.txt
Labels: v3.0

#10098 Chore: update Turkish translations
  packages/tools/locales/tr_TR.po
Labels: translation

#9722 Cli: Change Joplin Cloud login process
  packages/app-cli/app/command-sync.ts
Labels: enhancement, cli, v3.0

#10087 Mobile: Fixes #10065 filtered deleted and trash folder when counting active notebooks
  packages/app-mobile/components/NoteList.tsx
  packages/app-mobile/components/screens/Notes.tsx
  packages/lib/models/Folder.test.ts
  packages/lib/models/Folder.ts
Labels: gsoc-2024

#10076 Desktop: Fixes #10060: Fix "New note" button rendering when startup with Trash can selected.
  packages/app-desktop/gui/NoteListControls/NoteListControls.tsx
  packages/app-desktop/gui/NoteListWrapper/NoteListWrapper.tsx
Labels: gsoc-2024

#10021 Desktop: Resolves #9984: Allow 'All Notes' to have 'Toggle own sort order'
  packages/app-desktop/gui/Sidebar/Sidebar.tsx
Labels: gsoc-2024

#10127 Update da_DK.po
  packages/tools/locales/da_DK.po
Labels: translation

#10147 Mobile: Fixes #10143: Shows only the real folders in the dropdown of parent folders.
  packages/app-mobile/components/ScreenHeader.tsx
  packages/app-mobile/components/screens/folder.js
  packages/lib/models/Folder.test.ts
  packages/lib/models/Folder.ts
Labels: gsoc-2024

#10085 Desktop: Fixes #10077 - Special characters in notebooks and tags are not sorted alphabetically
  packages/app-desktop/gui/TagList.tsx
  packages/lib/BaseApplication.ts
  packages/lib/components/shared/side-menu-shared.ts
  packages/lib/models/Folder.test.ts
  packages/lib/models/Folder.ts
  packages/lib/models/Note.ts
  packages/lib/models/utils/getCollator.ts
Labels: gsoc-2024

#10193 Desktop: Fixes #10078: Fixed auto scrolling with moving a note
  packages/app-desktop/gui/NoteList/NoteList2.tsx
  packages/app-desktop/gui/NoteList/utils/useMoveNote.ts
Labels: gsoc-2024
