Repository laurent22/joplin, pull requests merged in 2024-05, with the labels that each got.

#10433 All: Fix logger tests by adding time
  packages/utils/Logger.test.ts
Labels: enhancement

#10432 Clipper: Improve logs to help debugging
  packages/lib/downloadController.ts
  packages/lib/services/rest/routes/notes.ts
Labels: enhancement, clipper

#10469 Desktop: Resolves #9959: Display description for settings field in the plugin customization screen
  packages/app-desktop/gui/ConfigScreen/ConfigScreen.tsx
Labels: bug, plugins

#10473 Chore: Refactor: Mobile: Rename CustomButton to IconButton
  .eslintignore
  .gitignore
  packages/app-mobile/components/Icon.tsx
  packages/app-mobile/components/IconButton.tsx
  packages/app-mobile/components/NoteEditor/MarkdownToolbar/ToggleOverflowButton.tsx
  packages/app-mobile/components/NoteEditor/MarkdownToolbar/ToggleSpaceButton.tsx
  packages/app-mobile/components/NoteEditor/MarkdownToolbar/ToolbarButton.tsx
  packages/app-mobile/components/NoteEditor/MarkdownToolbar/buttons/useActionButtons.ts
  packages/app-mobile/components/NoteEditor/SearchPanel.tsx
  packages/app-mobile/components/ScreenHeader/index.tsx
  packages/tools/cspell/dictionary4.txt
Labels: mobile

#10478 Update Swedish translation
  packages/tools/locales/sv.po
Labels: translation

#10500 All: Translation: Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#10470 Mobile: Improve dialog styling on large and notched screens
  packages/app-mobile/components/DismissibleDialog.tsx
  packages/app-mobile/components/Modal.tsx
Labels: mobile, plugins

#10436 Docs: Resolves #10341: Document the drawing option
  Assets/WebsiteAssets/images/draw/add-new-image.svg
  Assets/WebsiteAssets/images/draw/average-selection-color.png
  Assets/WebsiteAssets/images/draw/change-visible-region.png
  Assets/WebsiteAssets/images/draw/color-under-cursor.png
  Assets/WebsiteAssets/images/draw/desktop-create-new-drawing.png
  Assets/WebsiteAssets/images/draw/drawing-opened-in-other-apps.png
  Assets/WebsiteAssets/images/draw/edit-existing-drawing-on-desktop.mp4
  Assets/WebsiteAssets/images/draw/edit-from-viewer.svg
  Assets/WebsiteAssets/images/draw/editor-toolbar-top.svg
  Assets/WebsiteAssets/images/draw/help-icon.png
  Assets/WebsiteAssets/images/draw/infinite-zoom-demo.mp4
  Assets/WebsiteAssets/images/draw/lock-rotation.png
  Assets/WebsiteAssets/images/draw/long-press-edit.svg
  Assets/WebsiteAssets/images/draw/pick-color-from-screen.svg
  Assets/WebsiteAssets/images/draw/restore-auto-resize.png
  Assets/WebsiteAssets/images/draw/show-pen-menu.svg
  packages/tools/cspell/dictionary4.txt
  readme/apps/drawing_tool.md
Labels: documentation, draw

#10459 Desktop: Re-render note when resources are changed
  packages/app-desktop/gui/NoteEditor/utils/useFormNote.test.ts
  packages/app-desktop/gui/NoteEditor/utils/useFormNote.ts
  packages/lib/models/Resource.ts
Labels: desktop

#10458 Desktop: Fixes #10381: Fix plugin settings stored in `settings.json` are lost on startup
  packages/lib/models/Setting.test.ts
  packages/lib/models/Setting.ts
  packages/lib/models/settings/FileHandler.ts
Labels: bug, desktop, plugins

#10434 Desktop: Fixes #10230: Fix new note and to-do buttons greyed when initial selection is "all notes" or a tag
  packages/app-mobile/components/screens/Notes.tsx
  packages/app-mobile/root.tsx
  packages/lib/reducer.ts
Labels: desktop
