Repository laurent22/joplin, pull requests merged in 2024-04, with the labels that each got.

#10239 All: Translation: Update ko.po(2024-04-01)
  packages/tools/locales/ko.po
Labels: translation

#10204 Desktop: Fixes #10182: Detailed note list doesn't follow preferred date and time formats
  packages/lib/services/noteList/renderViewProps.test.ts
  packages/lib/services/noteList/renderViewProps.ts
Labels: gsoc-2024

#10248 Desktop: feat: Added search list for font input fields
  .eslintignore
  .gitignore
  packages/app-desktop/gui/ConfigScreen/ConfigScreen.tsx
  packages/app-desktop/gui/ConfigScreen/FontSearch.tsx
  packages/app-desktop/gui/ConfigScreen/style.scss
  packages/lib/models/Setting.ts
Labels: gsoc-2024

#10337 Clipper: Fix process stopping because one resource can't be created
  packages/lib/services/rest/routes/notes.test.ts
  packages/lib/services/rest/routes/notes.ts
  packages/lib/shim-init-node.ts
  packages/lib/types.ts
Labels: bug, clipper
