Repository laurent22/joplin, pull requests merged in 2024-08, with the labels that each got.

#10812 Desktop: Accessibility: Improve settings screen keyboard navigation and screen reader accessibility
  .eslintignore
  .gitignore
  packages/app-desktop/gui/Button/Button.tsx
  packages/app-desktop/gui/ConfigScreen/ConfigScreen.tsx
  packages/app-desktop/gui/ConfigScreen/Sidebar.tsx
  packages/app-desktop/gui/ConfigScreen/controls/FontSearch.tsx
  packages/app-desktop/gui/ConfigScreen/controls/SettingComponent.tsx
  packages/app-desktop/gui/ConfigScreen/controls/SettingDescription.tsx
  packages/app-desktop/gui/ConfigScreen/controls/SettingHeader.tsx
  packages/app-desktop/gui/ConfigScreen/controls/SettingLabel.tsx
  packages/app-desktop/gui/ConfigScreen/controls/ToggleAdvancedSettingsButton.tsx
  packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginBox.tsx
  packages/app-desktop/gui/ConfigScreen/controls/plugins/PluginsStates.tsx
  packages/app-desktop/gui/ConfigScreen/controls/plugins/SearchPlugins.tsx
  packages/app-desktop/gui/ConfigScreen/style.scss
  packages/app-desktop/gui/ConfigScreen/styles/index.scss
  packages/app-desktop/gui/ConfigScreen/styles/setting-description.scss
  packages/app-desktop/gui/ConfigScreen/styles/setting-header.scss
  packages/app-desktop/gui/ConfigScreen/styles/setting-label.scss
  packages/app-desktop/gui/ConfigScreen/styles/setting-tab-panel.scss
  packages/app-desktop/gui/EncryptionConfigScreen/EncryptionConfigScreen.tsx
  packages/app-desktop/gui/lib/ToggleButton/ToggleButton.tsx
  packages/app-desktop/integration-tests/main.spec.ts
  packages/app-desktop/integration-tests/models/MainScreen.ts
  packages/app-desktop/integration-tests/models/SettingsScreen.ts
  packages/app-desktop/integration-tests/settings.spec.ts
  packages/app-desktop/main.scss
  packages/lib/models/Setting.ts
  packages/lib/theme.ts
Labels: accessibility

#10814 Desktop: Fixes #10815: Fix Enter key submits dialogs even if a button has focus
  packages/app-desktop/gui/DialogButtonRow/useKeyboardHandler.ts
Labels: accessibility

#10819 Desktop: Accessibility: Improve keyboard navigation in the Markdown and note toolbar
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/Toolbar.tsx
  packages/app-desktop/gui/NoteToolbar/NoteToolbar.tsx
  packages/app-desktop/gui/ToggleEditorsButton/ToggleEditorsButton.tsx
  packages/app-desktop/gui/ToolbarBase.tsx
  packages/app-desktop/gui/ToolbarButton/ToolbarButton.tsx
  packages/app-desktop/gui/ToolbarButton/styles/index.ts
  packages/app-desktop/gui/styles/editor-toolbar.scss
  packages/app-desktop/gui/styles/index.scss
  packages/app-desktop/gui/styles/toolbar-button.scss
  packages/app-desktop/integration-tests/markdownEditor.spec.ts
  packages/app-desktop/integration-tests/models/NoteEditorScreen.ts
  packages/app-desktop/integration-tests/settings.spec.ts
Labels: desktop, accessibility

#10817 Desktop: Accessibility: Restore keyboard focus when closing a dialog
  packages/app-desktop/gui/Dialog.tsx
  packages/app-desktop/gui/styles/dialog-modal-layer.scss
  packages/app-desktop/integration-tests/goToAnything.spec.ts
  packages/app-desktop/package.json
  yarn.lock
Labels: desktop, accessibility

#10826 Desktop: Fixes #10740: Improve the reliability of fetching resources
  packages/lib/shim-init-node.ts
Labels: bug, desktop

#10816 Desktop: Accessibility: Fix screen reader doesn't read Goto Anything search results or help button label
  packages/app-desktop/gui/HelpButton.tsx
  packages/app-desktop/gui/ItemList.tsx
  packages/app-desktop/gui/styles/flat-button.scss
  packages/app-desktop/gui/styles/help-text.scss
  packages/app-desktop/gui/styles/index.scss
  packages/app-desktop/plugins/GotoAnything.tsx
Labels: desktop, accessibility

#10535 Desktop: Use Electron `safeStorage` for keychain support
  .eslintignore
  .gitignore
  packages/app-desktop/bridge.ts
  packages/app-desktop/main.js
  packages/app-mobile/root.tsx
  packages/lib/BaseApplication.ts
  packages/lib/models/Setting.ts
  packages/lib/models/settings/builtInMetadata.ts
  packages/lib/services/SettingUtils.ts
  packages/lib/services/keychain/KeychainService.test.ts
  packages/lib/services/keychain/KeychainService.ts
  packages/lib/services/keychain/KeychainServiceDriver.dummy.ts
  packages/lib/services/keychain/KeychainServiceDriver.electron.ts
  packages/lib/services/keychain/KeychainServiceDriver.mobile.ts
  packages/lib/services/keychain/KeychainServiceDriver.node.ts
  packages/lib/services/keychain/KeychainServiceDriverBase.ts
  packages/lib/shim.ts
  packages/lib/testing/test-utils.ts
Labels: v3.1

#10864 Translation: Updating Japanese translation file
  packages/tools/locales/ja_JP.po
Labels: translation

#10881 Desktop: Windows: Fix PDF, video, and audio rendering
  .eslintignore
  .gitignore
  packages/app-desktop/gui/NoteEditor/utils/useMarkupToHtml.ts
  packages/app-desktop/integration-tests/markdownEditor.spec.ts
  packages/app-desktop/integration-tests/resources/small-pdf.pdf
  packages/app-desktop/integration-tests/resources/video.mp4
  packages/app-desktop/integration-tests/util/extendedExpect.ts
  packages/app-desktop/integration-tests/util/test.ts
  packages/app-desktop/utils/customProtocols/handleCustomProtocols.ts
  packages/renderer/MdToHtml/renderMedia.ts
  packages/renderer/types.ts
  packages/renderer/utils.ts
Labels: desktop, windows

#10884 Chore: Windows: Fix `handleCustomProtocols` test
  packages/app-desktop/utils/customProtocols/handleCustomProtocols.test.ts
Labels: windows

#10886 Chore: Windows: Fix mobile plugin assets change when rebuilding the mobile app
  packages/app-mobile/tools/encodeAssets.js
Labels: windows

#10885 Chore: Windows: Fix building the desktop app clears the list of supported Rich Text Editor locales
  packages/app-desktop/tools/copyApplicationAssets.js
Labels: windows

#10932 Desktop: Accessibility: Improve note title focus handling
  .eslintignore
  .gitignore
  packages/app-desktop/commands/focusElement.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/useEditorCommands.ts
  packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/TinyMCE.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/TinyMCE/utils/useKeyboardRefocusHandler.ts
  packages/app-desktop/gui/NoteEditor/NoteTitle/NoteTitleBar.tsx
  packages/app-desktop/gui/NoteEditor/commands/focusElementNoteBody.ts
  packages/app-desktop/integration-tests/main.spec.ts
  packages/app-desktop/integration-tests/richTextEditor.spec.ts
  packages/editor/CodeMirror/createEditor.ts
  packages/editor/CodeMirror/utils/isCursorAtBeginning.ts
  packages/editor/types.ts
Labels: accessibility

#10944 Desktop: Add left/right arrow keys as expand/collapse shortcuts for notebooks
  packages/app-desktop/gui/Sidebar/FolderAndTagList.tsx
  packages/app-desktop/gui/Sidebar/hooks/useOnSidebarKeyDownHandler.ts
Labels: desktop, accessibility

#10940 Desktop: Accessibility: Improve note list keyboard and screen reader accessibility
  .eslintignore
  .gitignore
  packages/app-desktop/gui/NoteList/NoteList2.tsx
  packages/app-desktop/gui/NoteList/style.scss
  packages/app-desktop/gui/NoteList/utils/useActiveDescendantId.ts
  packages/app-desktop/gui/NoteList/utils/useFocusNote.ts
  packages/app-desktop/gui/NoteList/utils/useFocusVisible.ts
  packages/app-desktop/gui/NoteList/utils/useOnKeyDown.ts
  packages/app-desktop/gui/NoteListItem/NoteListItem.tsx
  packages/app-desktop/gui/NoteListItem/utils/getNoteElementIdFromJoplinId.ts
  packages/app-desktop/gui/NoteListItem/utils/prepareViewProps.ts
  packages/app-desktop/gui/NoteListItem/utils/useItemElement.ts
  packages/app-desktop/gui/utils/announceForAccessibility.ts
  packages/app-desktop/integration-tests/main.spec.ts
  packages/app-desktop/integration-tests/markdownEditor.spec.ts
  packages/app-desktop/integration-tests/models/MainScreen.ts
  packages/app-desktop/integration-tests/models/NoteList.ts
  packages/app-desktop/integration-tests/noteList.spec.ts
  packages/app-desktop/integration-tests/settings.spec.ts
  packages/app-desktop/main.scss
  packages/lib/BaseModel.ts
  packages/lib/services/noteList/defaultListRenderer.ts
  packages/lib/services/noteList/defaultMultiColumnsRenderer.ts
  packages/lib/services/plugins/api/noteListType.ts
  packages/tools/cspell/dictionary4.txt
Labels: desktop, accessibility
