Repository laurent22/joplin, pull requests merged in 2025-08, with the labels that each got.

#12832 Transcribe: Resolves #12831: Add support for transcribe server to the server docker compose configuration
  .env-sample
  .env-transcribe-sample
  docker-compose.server.yml
  packages/server/README.md
  packages/transcribe/README.md
  packages/transcribe/src/env.ts
  packages/transcribe/src/services/createQueue.ts
  packages/transcribe/src/services/queue/PgBossQueue.ts
  packages/transcribe/src/types.ts
Labels: transcribe

#12864 All: Translation: Update hu_HU.po
  packages/tools/locales/hu_HU.po
Labels: translation

#12876 Transcribe: Fixes #12862: Add log statement signaling that the startup has finished
  packages/transcribe/src/api/app.ts
Labels: bug, transcribe

#12869 Desktop: Fixes #12087: Add shortcut to toggle between editors
  packages/app-desktop/gui/MenuBar.tsx
  packages/app-desktop/gui/menuCommandNames.ts
  packages/lib/services/KeymapService.ts
Labels: bug, desktop

#12893 All: Translation: Update sv.po
  packages/tools/locales/sv.po
Labels: translation

#12905 All: Translation: Update tr_TR.po
  packages/tools/locales/tr_TR.po
Labels: translation

#12917 All: Translation: Update ro_RO.po and ro_MD.po
  packages/tools/locales/ro_MD.po
  packages/tools/locales/ro_RO.po
Labels: translation

#12950 All: Translation: Update sk_SK.po
  packages/tools/locales/sk_SK.po
Labels: translation

#12966 All: Translation: Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#12971 Translation: Update fi_FI.po
  packages/tools/locales/fi_FI.po
Labels: translation

#12951 Desktop: Upgrade to Electron v37.3.0
  packages/app-desktop/package.json
  packages/app-desktop/tools/electronRebuild.js
  yarn.lock
Labels: v3.4

#12927 Desktop,Mobile: Markdown editor: Toggle checkboxes on ctrl-click
  .eslintignore
  .gitignore
  packages/editor/CodeMirror/createEditor.ts
  packages/editor/CodeMirror/extensions/ctrlClickActionExtension.ts
  packages/editor/CodeMirror/extensions/ctrlClickCheckboxExtension.ts
  packages/editor/CodeMirror/extensions/links/ctrlClickLinksExtension.ts
  packages/editor/CodeMirror/extensions/rendering/replaceCheckboxes.ts
  packages/editor/CodeMirror/utils/markdown/getCheckboxAtPosition.ts
  packages/editor/CodeMirror/utils/markdown/toggleCheckboxAt.ts
Labels: markdown-editor

#12954 Mobile: Improve tag screen usability to allow add or remove tag with a single press, when the keyboard is open
  packages/app-mobile/components/ComboBox.tsx
  packages/app-mobile/components/SearchInput.tsx
  packages/app-mobile/components/TagEditor.tsx
Labels: mobile

#12999 Desktop,Mobile,Cli: Fixes #12648: Fix unshare action requires two syncs to be reflected locally
  packages/lib/Synchronizer.ts
Labels: sync

#13019 All: Translation: Update tr_TR.po
  packages/tools/locales/tr_TR.po
Labels: translation

#13041 All: Translation: Update es_ES.po
  packages/tools/locales/es_ES.po
Labels: translation

#13028 Moble: Fixes #12953: Allow the tag dialog to scroll when little screen space is available
  packages/app-mobile/components/ComboBox.tsx
  packages/app-mobile/components/Modal.tsx
  packages/app-mobile/components/ModalDialog.tsx
  packages/app-mobile/components/TagEditor.tsx
  packages/app-mobile/components/screens/NoteTagsDialog.tsx
  packages/app-mobile/utils/hooks/useKeyboardState.ts
Labels: mobile, accessibility

#13025 Desktop: Fixes #13024: OCR: Fix infinite loop
  packages/lib/services/ocr/OcrService.test.ts
  packages/lib/services/ocr/OcrService.ts
Labels: bug, v3.4

#12935 Mobile: Rich Text Editor: Fix additional blank lines added around list items on save
  .eslintignore
  .gitignore
  packages/app-mobile/components/NoteEditor/RichTextEditor.test.tsx
  packages/app-mobile/contentScripts/richTextEditorBundle/contentScript/index.ts
  packages/editor/ProseMirror/createEditor.ts
  packages/editor/ProseMirror/types.ts
  packages/editor/ProseMirror/utils/postprocessEditorOutput.test.ts
  packages/editor/ProseMirror/utils/postprocessEditorOutput.ts
Labels: mobile, editor

#12943 Mobile: Rich Text Editor: Avoid rendering links with unknown protocols
  packages/app-mobile/components/NoteEditor/RichTextEditor.test.tsx
  packages/app-mobile/contentScripts/richTextEditorBundle/contentScript/index.ts
  packages/editor/ProseMirror/schema.ts
Labels: mobile, editor, v3.4

#12967 Desktop, Mobile: Add a "highlight active line" setting
  .eslintignore
  .gitignore
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/CodeMirror.tsx
  packages/app-mobile/components/NoteEditor/NoteEditor.tsx
  packages/app-mobile/utils/hooks/useIsScreenReaderEnabled.ts
  packages/editor/CodeMirror/configFromSettings.ts
  packages/editor/CodeMirror/extensions/highlightActiveLineExtension.ts
  packages/editor/testing/createEditorSettings.ts
  packages/editor/types.ts
  packages/lib/models/settings/builtInMetadata.ts
Labels: markdown-editor

#13007 Linux, Windows: Fixes #12991, #12733: Fix notifications
  packages/app-desktop/main.ts
  packages/lib/services/AlarmServiceDriverNode.ts
Labels: linux, windows

#13060 Cli: Add commands for publishing and unpublishing notes with Joplin Server
  .eslintignore
  .gitignore
  packages/app-cli/app/command-publish.test.ts
  packages/app-cli/app/command-publish.ts
  packages/app-cli/app/command-unpublish.test.ts
  packages/app-cli/app/command-unpublish.ts
Labels: cli

#13068 Desktop: Fixes #12816: Accessibility: Fix dismissing the alarm dialog by pressing escape
  packages/app-desktop/gui/PromptDialog.tsx
Labels: accessibility

#13069 Android: Fixes #12952: External keyboard: Fix adding tags by pressing enter on certain Android devices
  packages/app-mobile/components/ComboBox.tsx
Labels: tags, accessibility

#13077 Mobile: Plugin API: Fix compatibility with certain plugins targetting the desktop app
  packages/app-mobile/services/commands/stateToWhenClauseContext.ts
Labels: mobile, plugins, v3.4
