Repository laurent22/joplin, pull requests merged in 2025-03, with the labels that each got.

#11913 updating Spanish translation strings
  packages/tools/locales/es_ES.po
Labels: translation

#11920 Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#11918 Desktop: Accessibility: Improve "toggle all notebooks" accessibility
  packages/app-desktop/gui/Sidebar/hooks/useOnRenderListWrapper.tsx
Labels: desktop, accessibility

#11917 Desktop: Make "toggle all folders" button also expand the folder list
  .eslintignore
  .gitignore
  packages/lib/commands/toggleAllFolders.test.ts
  packages/lib/commands/toggleAllFolders.ts
Labels: desktop

#11922 Translation improvement for zh_CN
  packages/tools/locales/zh_CN.po
Labels: translation

#11921 Desktop: improve download in install script
  Joplin_install_and_update.sh
Labels: linux

#11937 All: Translation: Update ru_RU.po
  packages/tools/locales/ru_RU.po
Labels: translation

#11942 Desktop: Fixes #11939: Render audio embedding as a resource to a link
  packages/app-cli/tests/support/onenote/note_with_audio_embedded.zip
  packages/lib/services/interop/InteropService_Importer_OneNote.test.ts
  packages/lib/services/interop/__snapshots__/InteropService_Importer_OneNote.test.js.snap
  packages/onenote-converter/src/page/embedded_file.rs
Labels: bug, desktop

#11931 iOS: Accessibility: Fix plugins can't be installed using VoiceOver
  packages/app-mobile/components/screens/ConfigScreen/plugins/PluginBox/index.tsx
Labels: iOS, accessibility

#11929 Mobile: Accessibility: Improve focus handling in the note actions menu and modal dialogs
  .eslintignore
  .gitignore
  packages/app-mobile/components/Modal.tsx
  packages/app-mobile/components/ScreenHeader/Menu.tsx
  packages/app-mobile/components/SideMenu.tsx
  packages/app-mobile/components/accessibility/AccessibleView.test.tsx
  packages/app-mobile/components/accessibility/AccessibleView.tsx
  packages/app-mobile/components/accessibility/FocusControl/AutoFocusProvider.tsx
  packages/app-mobile/components/accessibility/FocusControl/FocusControl.tsx
  packages/app-mobile/components/accessibility/FocusControl/FocusControlProvider.tsx
  packages/app-mobile/components/accessibility/FocusControl/MainAppContent.tsx
  packages/app-mobile/components/accessibility/FocusControl/ModalWrapper.tsx
  packages/app-mobile/components/accessibility/FocusControl/types.ts
  packages/app-mobile/components/plugins/dialogs/PluginDialogManager.tsx
  packages/app-mobile/components/screens/ConfigScreen/plugins/testUtils/WrappedPluginStates.tsx
  packages/app-mobile/components/testing/TestProviderStack.tsx
  packages/app-mobile/components/voiceTyping/RecordingControls.tsx
  packages/app-mobile/root.tsx
  packages/tools/cspell/dictionary4.txt
  readme/dev/spec/modal_focus_management.md
Labels: mobile, accessibility

#11897 Docs: Accessibility: Document how to use the app with a screen reader
  readme/apps/screen_reader_accessibility.md
  readme/apps/search.md
Labels: documentation, accessibility

#11863 Docs: Resolves #11860: Add guidelines for making new contributions accessible
  packages/app-desktop/integration-tests/README.md
  readme/dev/accessibility.md
Labels: documentation, accessibility

#11962 Update hungarian translation
  packages/tools/locales/hu_HU.po
Labels: translation

#11960 Android: Resolves #11956: Voice typing: Transcribe more unprocessed audio after pressing "done"
  packages/app-mobile/components/voiceTyping/RecordingControls.tsx
  packages/app-mobile/components/voiceTyping/SpeechToTextBanner.tsx
  packages/app-mobile/services/voiceTyping/VoiceTyping.ts
  packages/app-mobile/services/voiceTyping/vosk.android.ts
  packages/app-mobile/services/voiceTyping/whisper.ts
Labels: android, Voice typing

#11967 Desktop: Accessibility: Add a menu item that moves focus to the note viewer
  .eslintignore
  .gitignore
  packages/app-desktop/gui/MenuBar.tsx
  packages/app-desktop/gui/NoteEditor/NoteBody/CodeMirror/v6/useEditorCommands.ts
  packages/app-desktop/gui/NoteEditor/commands/focusElementNoteViewer.ts
  packages/app-desktop/gui/NoteEditor/commands/index.ts
  packages/app-desktop/gui/NoteEditor/editorCommandDeclarations.ts
  packages/app-desktop/gui/NoteEditor/utils/useWindowCommandHandler.ts
  packages/app-desktop/gui/NoteTextViewer.tsx
  packages/app-desktop/gui/menuCommandNames.ts
  packages/app-desktop/gui/note-viewer/index.html
  packages/app-desktop/integration-tests/markdownEditor.spec.ts
Labels: desktop, accessibility

#11959 Web: Accessibility: Fix "sort notes by" button is sometimes not keyboard focusable
  packages/app-mobile/components/ScreenHeader/index.tsx
Labels: accessibility, web

#11957 Mobile: Accessibility: Make default modal close button accessible
  packages/app-mobile/components/Modal.tsx
Labels: mobile, accessibility

#11958 iOS: Accessibility: Fix focus gets stuck on "Attach" in the note actions menu
  packages/app-mobile/components/ScreenHeader/Menu.tsx
Labels: iOS, accessibility

#11983 Android: Voice typing: Improve processing with larger models
  packages/app-mobile/android/app/src/main/cpp/utils/WhisperSession.cpp
  packages/app-mobile/android/app/src/main/cpp/utils/WhisperSession.h
  packages/app-mobile/android/app/src/main/cpp/utils/findLongestSilence.cpp
  packages/app-mobile/android/app/src/main/cpp/utils/findLongestSilence.h
  packages/app-mobile/android/app/src/main/cpp/utils/findLongestSilence_test.cpp
  packages/app-mobile/android/app/src/main/cpp/whisperWrapper.cpp
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/AudioRecorder.kt
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/NativeWhisperLib.kt
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/SpeechToTextConverter.kt
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/SpeechToTextPackage.kt
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/SpeechToTextSessionManager.kt
  packages/app-mobile/components/voiceTyping/SpeechToTextBanner.tsx
  packages/app-mobile/services/voiceTyping/whisper.test.ts
  packages/app-mobile/services/voiceTyping/whisper.ts
Labels: android, Voice typing

#11979 Android: Resolves #11955: Voice typing: Improve re-download button UI
  packages/app-mobile/components/voiceTyping/SpeechToTextBanner.tsx
  packages/app-mobile/services/voiceTyping/VoiceTyping.ts
Labels: android, Voice typing

#11776 Desktop: Resolves #11741: Accessibility: Add screen reader announcements when toggling the note list and/or sidebar
  packages/app-desktop/gui/WindowCommandsAndDialogs/commands/toggleNoteList.ts
  packages/app-desktop/gui/WindowCommandsAndDialogs/commands/toggleSideBar.ts
  packages/app-desktop/gui/WindowCommandsAndDialogs/utils/useWindowControl.ts
Labels: desktop, accessibility

#12008 Android: Voice typing: Performance: Disable preview generation logic
  packages/app-mobile/android/app/src/main/cpp/utils/WhisperSession.cpp
  packages/app-mobile/android/app/src/main/cpp/utils/WhisperSession.h
  packages/app-mobile/android/app/src/main/cpp/whisperWrapper.cpp
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/NativeWhisperLib.kt
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/SpeechToTextConverter.kt
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/SpeechToTextPackage.kt
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/SpeechToTextSessionManager.kt
  packages/app-mobile/services/voiceTyping/whisper.test.ts
  packages/app-mobile/services/voiceTyping/whisper.ts
Labels: Voice typing

#12013 Android: Voice typing: Improve transcription at the end of paragraphs
  packages/app-mobile/android/app/src/main/cpp/utils/WhisperSession.cpp
Labels: Voice typing

#12015 Android: Voice typing: Disable "Download update" button while downloading an updated model
  packages/app-mobile/components/voiceTyping/SpeechToTextBanner.tsx
Labels: Voice typing

#12027 iOS: Fixes #11711: Fix Markdown toolbar partially covered by keyboard on some iOS devices
  .eslintignore
  .gitignore
  packages/app-mobile/components/ToggleSpaceButton.tsx
  packages/app-mobile/components/app-nav.tsx
  packages/app-mobile/components/screens/Note/Note.tsx
  packages/app-mobile/utils/hooks/useKeyboardState.ts
  packages/app-mobile/utils/hooks/useKeyboardVisible.ts
  packages/lib/models/settings/builtInMetadata.ts
Labels: iOS
