Repository laurent22/joplin, pull requests merged in 2025-06, with the labels that each got.

#12388 Desktop: Change how the main content size is determined
  packages/app-desktop/app.reducer.test.ts
  packages/app-desktop/app.reducer.ts
  packages/app-desktop/app.ts
  packages/app-desktop/bridge.ts
  packages/app-desktop/commands/exportDeletionLog.test.ts
  packages/app-desktop/gui/Navigator.tsx
  packages/app-desktop/gui/Root.tsx
  packages/app-desktop/services/sortOrder/PerFolderSortOrderService.test.ts
Labels: desktop

#12381 Desktop, Mobile: Fixes #12097: Add ability to delete all history for individual notes
  .eslintignore
  .gitignore
  packages/app-desktop/gui/NoteRevisionViewer.tsx
  packages/app-mobile/components/screens/NoteRevisionViewer.tsx
  packages/lib/components/shared/NoteRevisionViewer/useDeleteHistoryClick.ts
  packages/lib/models/Revision.ts
Labels: mobile, desktop

#12386 All: Fixes #12362: Fixes resources linked with Windows path not being imported
  packages/app-cli/tests/support/test_notes/md/windows_path.html
  packages/lib/services/interop/InteropService_Importer_Md.test.ts
  packages/lib/services/interop/InteropService_Importer_Md.ts
Labels: bug, import

#12402 Android: Voice typing: Fix memory leak
  packages/app-mobile/android/app/src/main/cpp/whisperWrapper.cpp
Labels: Voice typing

#12404 Android: Voice typing: Improve silence detection
  packages/app-mobile/android/app/src/main/cpp/utils/WhisperSession.cpp
Labels: Voice typing

#12453 Chore: Web: Fix `TypeMismatchWarning` logged frequently on startup in dev mode
  packages/app-mobile/utils/fs-driver/fs-driver-rn.web.worker.ts
Labels: web

#12452 Chore: Desktop: Fix layout-related warning shown in console on startup
  packages/app-desktop/gui/Navigator.tsx
Labels: desktop

#12476 Chore: Mobile: Fix "missing `act()`" warning
  packages/app-mobile/components/screens/Note/Note.test.tsx
Labels: ci

#12482 Chore: CI: Fix plugin-related test failure
  packages/app-cli/tests/services/plugins/PluginService.ts
Labels: ci

#12546 All: Translation: Update sv.po
  packages/tools/locales/sv.po
Labels: translation

#12562 All: Translation: Update hu_HU.po
  packages/tools/locales/hu_HU.po
Labels: translation

#12370 Android: Voice typing: Add setting to allow specifying a glossary
  packages/app-mobile/services/voiceTyping/whisper.test.ts
  packages/app-mobile/services/voiceTyping/whisper.ts
  packages/lib/locale.ts
  packages/lib/models/settings/builtInMetadata.ts
  readme/dev/spec/voice_typing.md
Labels: android, Voice typing

#12566 CI: Fixes #12440: Disable logging from onenote-converter library by checking if it a test run
  packages/lib/services/interop/InteropService_Importer_OneNote.test.ts
Labels: bug, ci

#12588 All: Translation: Update sk_SK.po
  packages/tools/locales/sk_SK.po
Labels: translation
