Repository laurent22/joplin, pull requests merged in 2025-09, with the labels that each got.

#13132 Mobile: Fix light bar shown above header in dark mode
  packages/app-mobile/components/ScreenHeader/index.tsx
Labels: v3.4

#13131 Mobile: Plugins: Fix renderer plugins that use the `settingValue` API
  packages/app-mobile/contentScripts/rendererBundle/useWebViewSetup.ts
Labels: v3.4

#13090 Cli: Fix last change sometimes lost when not in TUI mode
  packages/app-cli/app/app.ts
  packages/lib/BaseApplication.ts
  packages/lib/database-driver-node.js
  packages/lib/database.ts
Labels: bug, cli

#13092 Server: Fixes #12984: Improve handling of concurrent deletion requests for the same item
  packages/server/src/models/ItemModel.test.ts
  packages/server/src/models/ItemModel.ts
  packages/server/src/routes/api/items.test.ts
  packages/server/src/routes/api/items.ts
  packages/server/src/utils/testing/apiUtils.ts
  packages/server/src/utils/testing/testUtils.ts
Labels: server

#13163 All: Translation: Update sv.po
  packages/tools/locales/sv.po
Labels: translation

#13170 All: Translation: Update sv.po
  packages/tools/locales/sv.po
Labels: translation

#13174 Mobile: Rich Text Editor: Accessibility: Fix font size setting not respected
  packages/app-mobile/contentScripts/richTextEditorBundle/useWebViewSetup.ts
  packages/editor/types.ts
Labels: mobile, editor

#12931 Desktop, Mobile: Add support for mixed case tags
  packages/app-mobile/components/ComboBox.test.tsx
  packages/app-mobile/components/ComboBox.tsx
  packages/app-mobile/components/TagEditor.test.tsx
  packages/app-mobile/components/TagEditor.tsx
  packages/app-mobile/components/screens/tags.tsx
  packages/lib/models/Tag.test.ts
  packages/lib/models/Tag.ts
  packages/lib/services/interop/InteropService_Importer_Md_frontmatter.test.ts
Labels: tags, v3.5

#12989 Desktop, Mobile: Automatically retrigger the sync if there are more unsynced outgoing changes when sync completes
  packages/lib/Synchronizer.ts
Labels: mobile, desktop, cli, sync, v3.5

#13016 Mobile: Resolves #12936: Allow expanding and collapsing the title field across multiple lines
  packages/app-mobile/components/screens/Note/Note.tsx
  packages/app-mobile/components/screens/NoteRevisionViewer.tsx
Labels: v3.5

#13256 All: Translations: Update hu_HU.po
  packages/tools/locales/hu_HU.po
Labels: translation

#13248 Android: Improve location permission request
  packages/app-mobile/components/screens/ConfigScreen/ConfigScreen.tsx
  packages/app-mobile/components/screens/Note/Note.tsx
  packages/app-mobile/utils/checkPermissions.ts
Labels: android

#13283 Desktop: Accessibility: Disable sync icon animation when reduce motion is enabled
  packages/app-desktop/gui/Button/Button.tsx
  packages/app-desktop/gui/Sidebar/Sidebar.tsx
  packages/app-desktop/gui/Sidebar/style.scss
  packages/app-desktop/gui/Sidebar/styles/sidebar-sync-button.scss
  packages/app-desktop/main.scss
Labels: accessibility

#13259 Mobile: Improve inline search performance in large documents
  packages/app-mobile/components/NoteEditor/NoteEditor.tsx
  packages/app-mobile/components/NoteEditor/SearchPanel.tsx
  packages/app-mobile/contentScripts/markdownEditorBundle/useWebViewSetup.ts
  packages/app-mobile/contentScripts/richTextEditorBundle/contentScript/index.ts
  packages/editor/CodeMirror/CodeMirrorControl.ts
  packages/editor/CodeMirror/extensions/searchExtension.ts
  packages/editor/ProseMirror/createEditor.ts
  packages/editor/ProseMirror/plugins/searchPlugin.ts
  packages/editor/events.ts
  packages/editor/types.ts
Labels: mobile, editor

#13169 Mobile: Resolves #13104: Accessibility: Allow changing the ALT text of images from the mobile Rich Text Editor
  .eslintignore
  .gitignore
  packages/app-mobile/components/NoteEditor/RichTextEditor.test.tsx
  packages/app-mobile/components/NoteEditor/RichTextEditor.tsx
  packages/editor/ProseMirror/createEditor.ts
  packages/editor/ProseMirror/plugins/detailsPlugin.test.ts
  packages/editor/ProseMirror/plugins/imagePlugin.test.ts
  packages/editor/ProseMirror/plugins/imagePlugin.ts
  packages/editor/ProseMirror/plugins/joplinEditablePlugin/createEditorDialog.ts
  packages/editor/ProseMirror/plugins/joplinEditablePlugin/joplinEditablePlugin.test.ts
  packages/editor/ProseMirror/plugins/joplinEditablePlugin/joplinEditablePlugin.ts
  packages/editor/ProseMirror/plugins/resourcePlaceholderPlugin.ts
  packages/editor/ProseMirror/plugins/utils/createExternalEditorPlugin.ts
  packages/editor/ProseMirror/plugins/utils/createFloatingButtonPlugin.ts
  packages/editor/ProseMirror/schema.ts
  packages/editor/ProseMirror/styles.ts
  packages/editor/ProseMirror/styles/alt-text-editor.css
  packages/editor/ProseMirror/styles/floating-button-bar.css
  packages/editor/ProseMirror/styles/joplin-dialog.css
  packages/editor/ProseMirror/styles/joplin-editable.css
  packages/editor/ProseMirror/styles/joplin-image-view.css
  packages/editor/ProseMirror/styles/joplin-selectable.css
  packages/editor/ProseMirror/testing/createTestEditor.ts
  packages/editor/ProseMirror/testing/createTestEditorWithSerializer.ts
  packages/editor/ProseMirror/utils/SelectableNodeView.ts
  packages/editor/ProseMirror/utils/dom/createButton.ts
  packages/editor/ProseMirror/utils/dom/showModal.ts
  packages/editor/ProseMirror/utils/selectFirstInstanceOfNode.ts
Labels: mobile, editor
