Repository laurent22/joplin, pull requests merged in 2025-04, with the labels that each got.

#12028 Desktop: Resolves #11608: Increase the likelihood of text generation from image recognition
  packages/app-cli/tests/ocr_samples/low_confidence_testing.png
  packages/lib/services/ocr/OcrService.test.ts
  packages/lib/services/ocr/drivers/OcrDriverTesseract.ts
Labels: desktop

#11752 Desktop: Improve notification accessibility
  .eslintignore
  .gitignore
  packages/app-desktop/gui/MainScreen.tsx
  packages/app-desktop/gui/NotyfContext.tsx
  packages/app-desktop/gui/PluginNotification/PluginNotification.tsx
  packages/app-desktop/gui/PopupNotification/NotificationItem.tsx
  packages/app-desktop/gui/PopupNotification/PopupNotificationList.tsx
  packages/app-desktop/gui/PopupNotification/PopupNotificationProvider.tsx
  packages/app-desktop/gui/PopupNotification/types.ts
  packages/app-desktop/gui/Root.tsx
  packages/app-desktop/gui/TrashNotification/TrashNotification.tsx
  packages/app-desktop/gui/TrashNotification/TrashNotificationMessage.tsx
  packages/app-desktop/gui/TrashNotification/style.scss
  packages/app-desktop/gui/UpdateNotification/UpdateNotification.tsx
  packages/app-desktop/gui/UpdateNotification/style.scss
  packages/app-desktop/gui/WindowCommandsAndDialogs/WindowCommandsAndDialogs.tsx
  packages/app-desktop/gui/styles/index.scss
  packages/app-desktop/gui/styles/link-button.scss
  packages/app-desktop/gui/styles/popup-notification-item.scss
  packages/app-desktop/gui/styles/popup-notification-list.scss
  packages/app-desktop/index.html
  packages/app-desktop/integration-tests/noteList.spec.ts
  packages/app-desktop/main.scss
  packages/app-desktop/package.json
  packages/app-desktop/style.scss
  packages/tools/cspell/dictionary4.txt
  yarn.lock
Labels: desktop, accessibility

#12134 All: Translation: Update ro.po
  packages/tools/locales/ro.po
Labels: translation

#12156 All: Translation: Update zh_CN.po
  packages/tools/locales/zh_CN.po
Labels: translation

#12155 All: Translation: Add ro_MD.po
  packages/tools/locales/ro_MD.po
  packages/tools/locales/ro_RO.po
Labels: translation

#12165 All: Translation: Update hu_HU.po
  packages/tools/locales/hu_HU.po
Labels: translation

#12169 All: Translation: Update id_ID.po
  packages/tools/locales/id_ID.po
Labels: translation

#12183 Desktop: Accessibility: Fix "focus viewer" doesn't move foucs to the correct line for sufficiently large documents
  packages/app-desktop/gui/note-viewer/index.html
Labels: accessibility

#12161 All: Translation: Update fr_FR.po
  packages/tools/locales/fr_FR.po
Labels: translation

#12188 All: Translation: Update sk_SK.po
  packages/tools/locales/sk_SK.po
Labels: translation
