Repository laurent22/joplin, pull requests merged in 2025-05, with the labels that each got.

#12025 Desktop: Resolves #11774: Add Sign Up call to Joplin Cloud
  .eslintignore
  .gitignore
  packages/app-desktop/gui/JoplinCloudLoginScreen.tsx
  packages/app-desktop/gui/JoplinCloudSignUpCallToAction.tsx
  packages/app-desktop/gui/SyncWizard/Dialog.tsx
  packages/app-desktop/gui/styles/index.scss
  packages/app-desktop/gui/styles/joplin-cloud-sign-up.scss
Labels: desktop

#12205 All: Translation: Update sk_SK.po
  packages/tools/locales/sk_SK.po
Labels: translation

#12206 All: Translation: Update hu_HU.po
  packages/tools/locales/hu_HU.po
Labels: translation

#12211 All: Translation: Update ro_RO.po and ro_MD.po
  packages/tools/locales/ro_MD.po
  packages/tools/locales/ro_RO.po
Labels: translation

#12221 All: Translation: Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#12219 Windows: Fix printing
  packages/app-desktop/InteropServiceHelper.ts
Labels: v3.3

#12213 Desktop: Fixes #12204: Fix crash after removing "toggle tab indentation" keyboard shortcut
  packages/lib/services/KeymapService.test.js
  packages/lib/services/KeymapService.ts
Labels: v3.3

#12231 All: Translation: Update ro_RO.po and ro_MD.po
  packages/tools/locales/ro_MD.po
  packages/tools/locales/ro_RO.po
Labels: translation

#12242 All: Translation: Update tr_TR.po
  packages/tools/locales/tr_TR.po
Labels: translation

#12252 All: Translation: Update hu_HU.po
  packages/tools/locales/hu_HU.po
Labels: translation

#12255 Update da_DK.po
  packages/tools/locales/da_DK.po
Labels: translation

#12256 Update gl_ES.po
  packages/tools/locales/gl_ES.po
Labels: translation

#12257 Revert "All: Translation: Update ro_RO.po and ro_MD.po"
  packages/tools/locales/ro_MD.po
  packages/tools/locales/ro_RO.po
Labels: translation

#12311 All: Translation: Update hu_HU.po
  packages/tools/locales/hu_HU.po
Labels: translation

#12310 All: Translation: Update ro_RO.po and ro_MD.po
  packages/tools/locales/ro_MD.po
  packages/tools/locales/ro_RO.po
Labels: translation

#12316 All: Translation: Update de_DE.po
  packages/tools/locales/de_DE.po
Labels: translation

#12351 Android: Fix voice typing fails to start on certain devices
  packages/app-mobile/android/app/src/main/java/net/cozic/joplin/audio/AudioRecorder.kt
Labels: Voice typing
